<?php

namespace Database\Seeders;

use App\Models\Reference\Continent;
use App\Models\Reference\Country;
use App\Models\Reference\Region;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Un49LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('continents')->truncate();
        DB::table('regions')->truncate();
        DB::table('countries')->truncate();

        Continent::create(['id' => '002', 'name' => 'Africa']);
        Continent::create(['id' => '019', 'name' => 'Americas']);
        Continent::create(['id' => '142', 'name' => 'Asia']);
        Continent::create(['id' => '150', 'name' => 'Europe']);
        Continent::create(['id' => '009', 'name' => 'Oceania']);

        Region::create(['continent_id' => '002', 'id' => '015', 'name' => 'Northern Africa']);

        Region::create(['continent_id' => '002', 'id' => '202', 'name' => 'Sub-Saharan Africa']);
        Region::create(['continent_id' => '002', 'id' => '014', 'parent_id' => '202', 'name' => 'Eastern Africa']);
        Region::create(['continent_id' => '002', 'id' => '017', 'parent_id' => '202', 'name' => 'Middle Africa']);
        Region::create(['continent_id' => '002', 'id' => '018', 'parent_id' => '202', 'name' => 'Southern Africa']);
        Region::create(['continent_id' => '002', 'id' => '011', 'parent_id' => '202', 'name' => 'Western Africa']);

        Region::create(['continent_id' => '019', 'id' => '419', 'name' => 'Latin America and the Caribbean']);
        Region::create(['continent_id' => '019', 'id' => '029', 'parent_id' => '419', 'name' => 'Caribbean']);
        Region::create(['continent_id' => '019', 'id' => '013', 'parent_id' => '419',  'name' => 'Central America']);
        Region::create(['continent_id' => '019', 'id' => '005', 'parent_id' => '419',  'name' => 'South America']);

        Region::create(['continent_id' => '019', 'id' => '021', 'name' => 'Northern America']);
        Region::create(['continent_id' => '142', 'id' => '143', 'name' => 'Central Asia']);
        Region::create(['continent_id' => '142', 'id' => '030', 'name' => 'Eastern Asia']);
        Region::create(['continent_id' => '142', 'id' => '035', 'name' => 'South-eastern Asia']);
        Region::create(['continent_id' => '142', 'id' => '034', 'name' => 'Southern Asia']);
        Region::create(['continent_id' => '142', 'id' => '145', 'name' => 'Western Asia']);
        Region::create(['continent_id' => '150', 'id' => '151', 'name' => 'Eastern Europe']);
        Region::create(['continent_id' => '150', 'id' => '154', 'name' => 'Northern Europe']);
        Region::create(['continent_id' => '150', 'id' => '830', 'name' => 'Channel Islands']);
        Region::create(['continent_id' => '150', 'id' => '039', 'name' => 'Southern Europe']);
        Region::create(['continent_id' => '150', 'id' => '155', 'name' => 'Western Europe']);
        Region::create(['continent_id' => '009', 'id' => '053', 'name' => 'Australia and New Zealand']);
        Region::create(['continent_id' => '009', 'id' => '054', 'name' => 'Melanesia']);
        Region::create(['continent_id' => '009', 'id' => '057', 'name' => 'Micronesia']);
        Region::create(['continent_id' => '009', 'id' => '061', 'name' => 'Polynesia']);

        Country::create(['region_id' => '015', 'name' => 'Algeria', 'id' => '012', 'iso_alpha2' => 'DZ', 'iso_alpha3' => 'DZA']);
        Country::create(['region_id' => '015', 'name' => 'Egypt', 'id' => '818', 'iso_alpha2' => 'EG', 'iso_alpha3' => 'EGY']);
        Country::create(['region_id' => '015', 'name' => 'Libya', 'id' => '434', 'iso_alpha2' => 'LY', 'iso_alpha3' => 'LBY']);
        Country::create(['region_id' => '015', 'name' => 'Morocco', 'id' => '504', 'iso_alpha2' => 'MA', 'iso_alpha3' => 'MAR']);
        Country::create(['region_id' => '015', 'name' => 'Sudan', 'id' => '729', 'iso_alpha2' => 'SD', 'iso_alpha3' => 'SDN']);
        Country::create(['region_id' => '015', 'name' => 'Tunisia', 'id' => '788', 'iso_alpha2' => 'TN', 'iso_alpha3' => 'TUN']);
        Country::create(['region_id' => '015', 'name' => 'Western Sahara', 'id' => '732', 'iso_alpha2' => 'EH', 'iso_alpha3' => 'ESH']);
        Country::create(['region_id' => '014', 'name' => 'British Indian Ocean Territory', 'id' => '086', 'iso_alpha2' => 'IO', 'iso_alpha3' => 'IOT']);
        Country::create(['region_id' => '014', 'name' => 'Burundi', 'id' => '108', 'iso_alpha2' => 'BI', 'iso_alpha3' => 'BDI']);
        Country::create(['region_id' => '014', 'name' => 'Comoros', 'id' => '174', 'iso_alpha2' => 'KM', 'iso_alpha3' => 'COM']);
        Country::create(['region_id' => '014', 'name' => 'Djibouti', 'id' => '262', 'iso_alpha2' => 'DJ', 'iso_alpha3' => 'DJI']);
        Country::create(['region_id' => '014', 'name' => 'Eritrea', 'id' => '232', 'iso_alpha2' => 'ER', 'iso_alpha3' => 'ERI']);
        Country::create(['region_id' => '014', 'name' => 'Ethiopia', 'id' => '231', 'iso_alpha2' => 'ET', 'iso_alpha3' => 'ETH']);
        Country::create(['region_id' => '014', 'name' => 'French Southern Territories', 'id' => '260', 'iso_alpha2' => 'TF', 'iso_alpha3' => 'ATF']);
        Country::create(['region_id' => '014', 'name' => 'Kenya', 'id' => '404', 'iso_alpha2' => 'KE', 'iso_alpha3' => 'KEN']);
        Country::create(['region_id' => '014', 'name' => 'Madagascar', 'id' => '450', 'iso_alpha2' => 'MG', 'iso_alpha3' => 'MDG']);
        Country::create(['region_id' => '014', 'name' => 'Malawi', 'id' => '454', 'iso_alpha2' => 'MW', 'iso_alpha3' => 'MWI']);
        Country::create(['region_id' => '014', 'name' => 'Mauritius', 'id' => '480', 'iso_alpha2' => 'MU', 'iso_alpha3' => 'MUS']);
        Country::create(['region_id' => '014', 'name' => 'Mayotte', 'id' => '175', 'iso_alpha2' => 'YT', 'iso_alpha3' => 'MYT']);
        Country::create(['region_id' => '014', 'name' => 'Mozambique', 'id' => '508', 'iso_alpha2' => 'MZ', 'iso_alpha3' => 'MOZ']);
        Country::create(['region_id' => '014', 'name' => 'Réunion', 'id' => '638', 'iso_alpha2' => 'RE', 'iso_alpha3' => 'REU']);
        Country::create(['region_id' => '014', 'name' => 'Rwanda', 'id' => '646', 'iso_alpha2' => 'RW', 'iso_alpha3' => 'RWA']);
        Country::create(['region_id' => '014', 'name' => 'Seychelles', 'id' => '690', 'iso_alpha2' => 'SC', 'iso_alpha3' => 'SYC']);
        Country::create(['region_id' => '014', 'name' => 'Somalia', 'id' => '706', 'iso_alpha2' => 'SO', 'iso_alpha3' => 'SOM']);
        Country::create(['region_id' => '014', 'name' => 'South Sudan', 'id' => '728', 'iso_alpha2' => 'SS', 'iso_alpha3' => 'SSD']);
        Country::create(['region_id' => '014', 'name' => 'Uganda', 'id' => '800', 'iso_alpha2' => 'UG', 'iso_alpha3' => 'UGA']);
        Country::create(['region_id' => '014', 'name' => 'United Republic of Tanzania', 'id' => '834', 'iso_alpha2' => 'TZ', 'iso_alpha3' => 'TZA']);
        Country::create(['region_id' => '014', 'name' => 'Zambia', 'id' => '894', 'iso_alpha2' => 'ZM', 'iso_alpha3' => 'ZMB']);
        Country::create(['region_id' => '014', 'name' => 'Zimbabwe', 'id' => '716', 'iso_alpha2' => 'ZW', 'iso_alpha3' => 'ZWE']);
        Country::create(['region_id' => '017', 'name' => 'Angola', 'id' => '024', 'iso_alpha2' => 'AO', 'iso_alpha3' => 'AGO']);
        Country::create(['region_id' => '017', 'name' => 'Cameroon', 'id' => '120', 'iso_alpha2' => 'CM', 'iso_alpha3' => 'CMR']);
        Country::create(['region_id' => '017', 'name' => 'Central African Republic', 'id' => '140', 'iso_alpha2' => 'CF', 'iso_alpha3' => 'CAF']);
        Country::create(['region_id' => '017', 'name' => 'Chad', 'id' => '148', 'iso_alpha2' => 'TD', 'iso_alpha3' => 'TCD']);
        Country::create(['region_id' => '017', 'name' => 'Congo', 'id' => '178', 'iso_alpha2' => 'CG', 'iso_alpha3' => 'COG']);
        Country::create(['region_id' => '017', 'name' => 'Democratic Republic of the Congo', 'id' => '180', 'iso_alpha2' => 'CD', 'iso_alpha3' => 'COD']);
        Country::create(['region_id' => '017', 'name' => 'Equatorial Guinea', 'id' => '226', 'iso_alpha2' => 'GQ', 'iso_alpha3' => 'GNQ']);
        Country::create(['region_id' => '017', 'name' => 'Gabon', 'id' => '266', 'iso_alpha2' => 'GA', 'iso_alpha3' => 'GAB']);
        Country::create(['region_id' => '017', 'name' => 'Sao Tome and Principe', 'id' => '678', 'iso_alpha2' => 'ST', 'iso_alpha3' => 'STP']);
        Country::create(['region_id' => '018', 'name' => 'Botswana', 'id' => '072', 'iso_alpha2' => 'BW', 'iso_alpha3' => 'BWA']);
        Country::create(['region_id' => '018', 'name' => 'Eswatini', 'id' => '748', 'iso_alpha2' => 'SZ', 'iso_alpha3' => 'SWZ']);
        Country::create(['region_id' => '018', 'name' => 'Lesotho', 'id' => '426', 'iso_alpha2' => 'LS', 'iso_alpha3' => 'LSO']);
        Country::create(['region_id' => '018', 'name' => 'Namibia', 'id' => '516', 'iso_alpha2' => 'NA', 'iso_alpha3' => 'NAM']);
        Country::create(['region_id' => '018', 'name' => 'South Africa', 'id' => '710', 'iso_alpha2' => 'ZA', 'iso_alpha3' => 'ZAF']);
        Country::create(['region_id' => '011', 'name' => 'Benin', 'id' => '204', 'iso_alpha2' => 'BJ', 'iso_alpha3' => 'BEN']);
        Country::create(['region_id' => '011', 'name' => 'Burkina Faso', 'id' => '854', 'iso_alpha2' => 'BF', 'iso_alpha3' => 'BFA']);
        Country::create(['region_id' => '011', 'name' => 'Cabo Verde', 'id' => '132', 'iso_alpha2' => 'CV', 'iso_alpha3' => 'CPV']);
        Country::create(['region_id' => '011', 'name' => 'Côte d’Ivoire', 'id' => '384', 'iso_alpha2' => 'CI', 'iso_alpha3' => 'CIV']);
        Country::create(['region_id' => '011', 'name' => 'Gambia', 'id' => '270', 'iso_alpha2' => 'GM', 'iso_alpha3' => 'GMB']);
        Country::create(['region_id' => '011', 'name' => 'Ghana', 'id' => '288', 'iso_alpha2' => 'GH', 'iso_alpha3' => 'GHA']);
        Country::create(['region_id' => '011', 'name' => 'Guinea', 'id' => '324', 'iso_alpha2' => 'GN', 'iso_alpha3' => 'GIN']);
        Country::create(['region_id' => '011', 'name' => 'Guinea-Bissau', 'id' => '624', 'iso_alpha2' => 'GW', 'iso_alpha3' => 'GNB']);
        Country::create(['region_id' => '011', 'name' => 'Liberia', 'id' => '430', 'iso_alpha2' => 'LR', 'iso_alpha3' => 'LBR']);
        Country::create(['region_id' => '011', 'name' => 'Mali', 'id' => '466', 'iso_alpha2' => 'ML', 'iso_alpha3' => 'MLI']);
        Country::create(['region_id' => '011', 'name' => 'Mauritania', 'id' => '478', 'iso_alpha2' => 'MR', 'iso_alpha3' => 'MRT']);
        Country::create(['region_id' => '011', 'name' => 'Niger', 'id' => '562', 'iso_alpha2' => 'NE', 'iso_alpha3' => 'NER']);
        Country::create(['region_id' => '011', 'name' => 'Nigeria', 'id' => '566', 'iso_alpha2' => 'NG', 'iso_alpha3' => 'NGA']);
        Country::create(['region_id' => '011', 'name' => 'Saint Helena', 'id' => '654', 'iso_alpha2' => 'SH', 'iso_alpha3' => 'SHN']);
        Country::create(['region_id' => '011', 'name' => 'Senegal', 'id' => '686', 'iso_alpha2' => 'SN', 'iso_alpha3' => 'SEN']);
        Country::create(['region_id' => '011', 'name' => 'Sierra Leone', 'id' => '694', 'iso_alpha2' => 'SL', 'iso_alpha3' => 'SLE']);
        Country::create(['region_id' => '011', 'name' => 'Togo', 'id' => '768', 'iso_alpha2' => 'TG', 'iso_alpha3' => 'TGO']);
        Country::create(['region_id' => '029', 'name' => 'Anguilla', 'id' => '660', 'iso_alpha2' => 'AI', 'iso_alpha3' => 'AIA']);
        Country::create(['region_id' => '029', 'name' => 'Antigua and Barbuda', 'id' => '028', 'iso_alpha2' => 'AG', 'iso_alpha3' => 'ATG']);
        Country::create(['region_id' => '029', 'name' => 'Aruba', 'id' => '533', 'iso_alpha2' => 'AW', 'iso_alpha3' => 'ABW']);
        Country::create(['region_id' => '029', 'name' => 'Bahamas', 'id' => '044', 'iso_alpha2' => 'BS', 'iso_alpha3' => 'BHS']);
        Country::create(['region_id' => '029', 'name' => 'Barbados', 'id' => '052', 'iso_alpha2' => 'BB', 'iso_alpha3' => 'BRB']);
        Country::create(['region_id' => '029', 'name' => 'Bonaire, Sint Eustatius and Saba', 'id' => '535', 'iso_alpha2' => 'BQ', 'iso_alpha3' => 'BES']);
        Country::create(['region_id' => '029', 'name' => 'British Virgin Islands', 'id' => '092', 'iso_alpha2' => 'VG', 'iso_alpha3' => 'VGB']);
        Country::create(['region_id' => '029', 'name' => 'Cayman Islands', 'id' => '136', 'iso_alpha2' => 'KY', 'iso_alpha3' => 'CYM']);
        Country::create(['region_id' => '029', 'name' => 'Cuba', 'id' => '192', 'iso_alpha2' => 'CU', 'iso_alpha3' => 'CUB']);
        Country::create(['region_id' => '029', 'name' => 'Curaçao', 'id' => '531', 'iso_alpha2' => 'CW', 'iso_alpha3' => 'CUW']);
        Country::create(['region_id' => '029', 'name' => 'Dominica', 'id' => '212', 'iso_alpha2' => 'DM', 'iso_alpha3' => 'DMA']);
        Country::create(['region_id' => '029', 'name' => 'Dominican Republic', 'id' => '214', 'iso_alpha2' => 'do    ', 'iso_alpha3' => 'DOM']);
        Country::create(['region_id' => '029', 'name' => 'Grenada', 'id' => '308', 'iso_alpha2' => 'GD', 'iso_alpha3' => 'GRD']);
        Country::create(['region_id' => '029', 'name' => 'Guadeloupe', 'id' => '312', 'iso_alpha2' => 'GP', 'iso_alpha3' => 'GLP']);
        Country::create(['region_id' => '029', 'name' => 'Haiti', 'id' => '332', 'iso_alpha2' => 'HT', 'iso_alpha3' => 'HTI']);
        Country::create(['region_id' => '029', 'name' => 'Jamaica', 'id' => '388', 'iso_alpha2' => 'JM', 'iso_alpha3' => 'JAM']);
        Country::create(['region_id' => '029', 'name' => 'Martinique', 'id' => '474', 'iso_alpha2' => 'MQ', 'iso_alpha3' => 'MTQ']);
        Country::create(['region_id' => '029', 'name' => 'Montserrat', 'id' => '500', 'iso_alpha2' => 'MS', 'iso_alpha3' => 'MSR']);
        Country::create(['region_id' => '029', 'name' => 'Puerto Rico', 'id' => '630', 'iso_alpha2' => 'PR', 'iso_alpha3' => 'PRI']);
        Country::create(['region_id' => '029', 'name' => 'Saint Barthélemy', 'id' => '652', 'iso_alpha2' => 'BL', 'iso_alpha3' => 'BLM']);
        Country::create(['region_id' => '029', 'name' => 'Saint Kitts and Nevis', 'id' => '659', 'iso_alpha2' => 'KN', 'iso_alpha3' => 'KNA']);
        Country::create(['region_id' => '029', 'name' => 'Saint Lucia', 'id' => '662', 'iso_alpha2' => 'LC', 'iso_alpha3' => 'LCA']);
        Country::create(['region_id' => '029', 'name' => 'Saint Martin(French Part)', 'id' => '663', 'iso_alpha2' => 'MF', 'iso_alpha3' => 'MAF']);
        Country::create(['region_id' => '029', 'name' => 'Saint Vincent and the Grenadines', 'id' => '670', 'iso_alpha2' => 'VC', 'iso_alpha3' => 'VCT']);
        Country::create(['region_id' => '029', 'name' => 'Sint Maarten(Dutch part)', 'id' => '534', 'iso_alpha2' => 'SX', 'iso_alpha3' => 'SXM']);
        Country::create(['region_id' => '029', 'name' => 'Trinidad and Tobago', 'id' => '780', 'iso_alpha2' => 'TT', 'iso_alpha3' => 'TTO']);
        Country::create(['region_id' => '029', 'name' => 'Turks and Caicos Islands', 'id' => '796', 'iso_alpha2' => 'TC', 'iso_alpha3' => 'TCA']);
        Country::create(['region_id' => '029', 'name' => 'United States Virgin Islands', 'id' => '850', 'iso_alpha2' => 'VI', 'iso_alpha3' => 'VIR']);
        Country::create(['region_id' => '013', 'name' => 'Belize', 'id' => '084', 'iso_alpha2' => 'BZ', 'iso_alpha3' => 'BLZ']);
        Country::create(['region_id' => '013', 'name' => 'Costa Rica', 'id' => '188', 'iso_alpha2' => 'CR', 'iso_alpha3' => 'CRI']);
        Country::create(['region_id' => '013', 'name' => 'El Salvador', 'id' => '222', 'iso_alpha2' => 'SV', 'iso_alpha3' => 'SLV']);
        Country::create(['region_id' => '013', 'name' => 'Guatemala', 'id' => '320', 'iso_alpha2' => 'GT', 'iso_alpha3' => 'GTM']);
        Country::create(['region_id' => '013', 'name' => 'Honduras', 'id' => '340', 'iso_alpha2' => 'HN', 'iso_alpha3' => 'HND']);
        Country::create(['region_id' => '013', 'name' => 'Mexico', 'id' => '484', 'iso_alpha2' => 'MX', 'iso_alpha3' => 'MEX']);
        Country::create(['region_id' => '013', 'name' => 'Nicaragua', 'id' => '558', 'iso_alpha2' => 'NI', 'iso_alpha3' => 'NIC']);
        Country::create(['region_id' => '013', 'name' => 'Panama', 'id' => '591', 'iso_alpha2' => 'PA', 'iso_alpha3' => 'PAN']);
        Country::create(['region_id' => '005', 'name' => 'Argentina', 'id' => '032', 'iso_alpha2' => 'AR', 'iso_alpha3' => 'ARG']);
        Country::create(['region_id' => '005', 'name' => 'Bolivia(Plurinational State of)', 'id' => '068', 'iso_alpha2' => 'BO', 'iso_alpha3' => 'BOL']);
        Country::create(['region_id' => '005', 'name' => 'Bouvet Island', 'id' => '074', 'iso_alpha2' => 'BV', 'iso_alpha3' => 'BVT']);
        Country::create(['region_id' => '005', 'name' => 'Brazil', 'id' => '076', 'iso_alpha2' => 'BR', 'iso_alpha3' => 'BRA']);
        Country::create(['region_id' => '005', 'name' => 'Chile', 'id' => '152', 'iso_alpha2' => 'CL', 'iso_alpha3' => 'CHL']);
        Country::create(['region_id' => '005', 'name' => 'Colombia', 'id' => '170', 'iso_alpha2' => 'CO', 'iso_alpha3' => 'COL']);
        Country::create(['region_id' => '005', 'name' => 'Ecuador', 'id' => '218', 'iso_alpha2' => 'EC', 'iso_alpha3' => 'ECU']);
        Country::create(['region_id' => '005', 'name' => 'Falkland Islands(Malvinas)', 'id' => '238', 'iso_alpha2' => 'FK', 'iso_alpha3' => 'FLK']);
        Country::create(['region_id' => '005', 'name' => 'French Guiana', 'id' => '254', 'iso_alpha2' => 'GF', 'iso_alpha3' => 'GUF']);
        Country::create(['region_id' => '005', 'name' => 'Guyana', 'id' => '328', 'iso_alpha2' => 'GY', 'iso_alpha3' => 'GUY']);
        Country::create(['region_id' => '005', 'name' => 'Paraguay', 'id' => '600', 'iso_alpha2' => 'PY', 'iso_alpha3' => 'PRY']);
        Country::create(['region_id' => '005', 'name' => 'Peru', 'id' => '604', 'iso_alpha2' => 'PE', 'iso_alpha3' => 'PER']);
        Country::create(['region_id' => '005', 'name' => 'South Georgia and the South Sandwich Islands', 'id' => '239', 'iso_alpha2' => 'GS', 'iso_alpha3' => 'SGS']);
        Country::create(['region_id' => '005', 'name' => 'Suriname', 'id' => '740', 'iso_alpha2' => 'SR', 'iso_alpha3' => 'SUR']);
        Country::create(['region_id' => '005', 'name' => 'Uruguay', 'id' => '858', 'iso_alpha2' => 'UY', 'iso_alpha3' => 'URY']);
        Country::create(['region_id' => '005', 'name' => 'Venezuela (Bolivarian Republic of)', 'id' => '862', 'iso_alpha2' => 'VE', 'iso_alpha3' => 'VEN']);
        Country::create(['region_id' => '021', 'name' => 'Bermuda', 'id' => '060', 'iso_alpha2' => 'BM', 'iso_alpha3' => 'BMU']);
        Country::create(['region_id' => '021', 'name' => 'Canada', 'id' => '124', 'iso_alpha2' => 'CA', 'iso_alpha3' => 'CAN']);
        Country::create(['region_id' => '021', 'name' => 'Greenland', 'id' => '304', 'iso_alpha2' => 'GL', 'iso_alpha3' => 'GRL']);
        Country::create(['region_id' => '021', 'name' => 'Saint Pierre and Miquelon', 'id' => '666', 'iso_alpha2' => 'PM', 'iso_alpha3' => 'SPM']);
        Country::create(['region_id' => '021', 'name' => 'United States of America', 'id' => '840', 'iso_alpha2' => 'US', 'iso_alpha3' => 'USA']);
        Country::create(['region_id' => '000', 'name' => 'Antarctica', 'id' => '010', 'iso_alpha2' => 'AQ', 'iso_alpha3' => 'ATA']);
        Country::create(['region_id' => '143', 'name' => 'Kazakhstan', 'id' => '398', 'iso_alpha2' => 'KZ', 'iso_alpha3' => 'KAZ']);
        Country::create(['region_id' => '143', 'name' => 'Kyrgyzstan', 'id' => '417', 'iso_alpha2' => 'KG', 'iso_alpha3' => 'KGZ']);
        Country::create(['region_id' => '143', 'name' => 'Tajikistan', 'id' => '762', 'iso_alpha2' => 'TJ', 'iso_alpha3' => 'TJK']);
        Country::create(['region_id' => '143', 'name' => 'Turkmenistan', 'id' => '795', 'iso_alpha2' => 'TM', 'iso_alpha3' => 'TKM']);
        Country::create(['region_id' => '143', 'name' => 'Uzbekistan', 'id' => '860', 'iso_alpha2' => 'UZ', 'iso_alpha3' => 'UZB']);
        Country::create(['region_id' => '030', 'name' => 'China', 'id' => '156', 'iso_alpha2' => 'CN', 'iso_alpha3' => 'CHN']);
        Country::create(['region_id' => '030', 'name' => 'China, Hong Kong Special Administrative Region', 'id' => '344', 'iso_alpha2' => 'HK', 'iso_alpha3' => 'HKG']);
        Country::create(['region_id' => '030', 'name' => 'China, Macao Special Administrative Region', 'id' => '446', 'iso_alpha2' => 'MO', 'iso_alpha3' => 'MAC']);
        Country::create(['region_id' => '030', 'name' => "Democratic People's Republic of Korea", 'id' => '408', 'iso_alpha2' => 'KP', 'iso_alpha3' => 'PRK']);
        Country::create(['region_id' => '030', 'name' => 'Japan', 'id' => '392', 'iso_alpha2' => 'JP', 'iso_alpha3' => 'JPN']);
        Country::create(['region_id' => '030', 'name' => 'Mongolia', 'id' => '496', 'iso_alpha2' => 'MN', 'iso_alpha3' => 'MNG']);
        Country::create(['region_id' => '030', 'name' => 'Republic of Korea', 'id' => '410', 'iso_alpha2' => 'KR', 'iso_alpha3' => 'KOR']);
        Country::create(['region_id' => '035', 'name' => 'Brunei Darussalam', 'id' => '096', 'iso_alpha2' => 'BN', 'iso_alpha3' => 'BRN']);
        Country::create(['region_id' => '035', 'name' => 'Cambodia', 'id' => '116', 'iso_alpha2' => 'KH', 'iso_alpha3' => 'KHM']);
        Country::create(['region_id' => '035', 'name' => 'Indonesia', 'id' => '360', 'iso_alpha2' => 'ID', 'iso_alpha3' => 'IDN']);
        Country::create(['region_id' => '035', 'name' => "Lao People's Democratic Republic", 'id' => '418', 'iso_alpha2' => 'LA', 'iso_alpha3' => 'LAO']);
        Country::create(['region_id' => '035', 'name' => 'Malaysia', 'id' => '458', 'iso_alpha2' => 'MY', 'iso_alpha3' => 'MYS']);
        Country::create(['region_id' => '035', 'name' => 'Myanmar', 'id' => '104', 'iso_alpha2' => 'MM', 'iso_alpha3' => 'MMR']);
        Country::create(['region_id' => '035', 'name' => 'Philippines', 'id' => '608', 'iso_alpha2' => 'PH', 'iso_alpha3' => 'PHL']);
        Country::create(['region_id' => '035', 'name' => 'Singapore', 'id' => '702', 'iso_alpha2' => 'SG', 'iso_alpha3' => 'SGP']);
        Country::create(['region_id' => '035', 'name' => 'Thailand', 'id' => '764', 'iso_alpha2' => 'TH', 'iso_alpha3' => 'THA']);
        Country::create(['region_id' => '035', 'name' => 'Timor - Leste', 'id' => '626', 'iso_alpha2' => 'TL', 'iso_alpha3' => 'TLS']);
        Country::create(['region_id' => '035', 'name' => 'Viet Nam', 'id' => '704', 'iso_alpha2' => 'VN', 'iso_alpha3' => 'VNM']);
        Country::create(['region_id' => '034', 'name' => 'Afghanistan', 'id' => '004', 'iso_alpha2' => 'AF', 'iso_alpha3' => 'AFG']);
        Country::create(['region_id' => '034', 'name' => 'Bangladesh', 'id' => '050', 'iso_alpha2' => 'BD', 'iso_alpha3' => 'BGD']);
        Country::create(['region_id' => '034', 'name' => 'Bhutan', 'id' => '064', 'iso_alpha2' => 'BT', 'iso_alpha3' => 'BTN']);
        Country::create(['region_id' => '034', 'name' => 'India', 'id' => '356', 'iso_alpha2' => 'IN', 'iso_alpha3' => 'IND']);
        Country::create(['region_id' => '034', 'name' => 'Iran(Islamic Republic of)', 'id' => '364', 'iso_alpha2' => 'IR', 'iso_alpha3' => 'IRN']);
        Country::create(['region_id' => '034', 'name' => 'Maldives', 'id' => '462', 'iso_alpha2' => 'MV', 'iso_alpha3' => 'MDV']);
        Country::create(['region_id' => '034', 'name' => 'Nepal', 'id' => '524', 'iso_alpha2' => 'NP', 'iso_alpha3' => 'NPL']);
        Country::create(['region_id' => '034', 'name' => 'Pakistan', 'id' => '586', 'iso_alpha2' => 'PK', 'iso_alpha3' => 'PAK']);
        Country::create(['region_id' => '034', 'name' => 'Sri Lanka', 'id' => '144', 'iso_alpha2' => 'LK', 'iso_alpha3' => 'LKA']);
        Country::create(['region_id' => '145', 'name' => 'Armenia', 'id' => '051', 'iso_alpha2' => 'AM', 'iso_alpha3' => 'ARM']);
        Country::create(['region_id' => '145', 'name' => 'Azerbaijan', 'id' => '031', 'iso_alpha2' => 'AZ', 'iso_alpha3' => 'AZE']);
        Country::create(['region_id' => '145', 'name' => 'Bahrain', 'id' => '048', 'iso_alpha2' => 'BH', 'iso_alpha3' => 'BHR']);
        Country::create(['region_id' => '145', 'name' => 'Cyprus', 'id' => '196', 'iso_alpha2' => 'CY', 'iso_alpha3' => 'CYP']);
        Country::create(['region_id' => '145', 'name' => 'Georgia', 'id' => '268', 'iso_alpha2' => 'GE', 'iso_alpha3' => 'GEO']);
        Country::create(['region_id' => '145', 'name' => 'Iraq', 'id' => '368', 'iso_alpha2' => 'IQ', 'iso_alpha3' => 'IRQ']);
        Country::create(['region_id' => '145', 'name' => 'Israel', 'id' => '376', 'iso_alpha2' => 'IL', 'iso_alpha3' => 'ISR']);
        Country::create(['region_id' => '145', 'name' => 'Jordan', 'id' => '400', 'iso_alpha2' => 'JO', 'iso_alpha3' => 'JOR']);
        Country::create(['region_id' => '145', 'name' => 'Kuwait', 'id' => '414', 'iso_alpha2' => 'KW', 'iso_alpha3' => 'KWT']);
        Country::create(['region_id' => '145', 'name' => 'Lebanon', 'id' => '422', 'iso_alpha2' => 'LB', 'iso_alpha3' => 'LBN']);
        Country::create(['region_id' => '145', 'name' => 'Oman', 'id' => '512', 'iso_alpha2' => 'OM', 'iso_alpha3' => 'OMN']);
        Country::create(['region_id' => '145', 'name' => 'Qatar', 'id' => '634', 'iso_alpha2' => 'QA', 'iso_alpha3' => 'QAT']);
        Country::create(['region_id' => '145', 'name' => 'Saudi Arabia', 'id' => '682', 'iso_alpha2' => 'SA', 'iso_alpha3' => 'SAU']);
        Country::create(['region_id' => '145', 'name' => 'State of Palestine', 'id' => '275', 'iso_alpha2' => 'PS', 'iso_alpha3' => 'PSE']);
        Country::create(['region_id' => '145', 'name' => 'Syrian Arab Republic', 'id' => '760', 'iso_alpha2' => 'SY', 'iso_alpha3' => 'SYR']);
        Country::create(['region_id' => '145', 'name' => 'Türkiye', 'id' => '792', 'iso_alpha2' => 'TR', 'iso_alpha3' => 'TUR']);
        Country::create(['region_id' => '145', 'name' => 'United Arab Emirates', 'id' => '784', 'iso_alpha2' => 'AE', 'iso_alpha3' => 'ARE']);
        Country::create(['region_id' => '145', 'name' => 'Yemen', 'id' => '887', 'iso_alpha2' => 'YE', 'iso_alpha3' => 'YEM']);
        Country::create(['region_id' => '151', 'name' => 'Belarus', 'id' => '112', 'iso_alpha2' => 'BY', 'iso_alpha3' => 'BLR']);
        Country::create(['region_id' => '151', 'name' => 'Bulgaria', 'id' => '100', 'iso_alpha2' => 'BG', 'iso_alpha3' => 'BGR']);
        Country::create(['region_id' => '151', 'name' => 'Czechia', 'id' => '203', 'iso_alpha2' => 'CZ', 'iso_alpha3' => 'CZE']);
        Country::create(['region_id' => '151', 'name' => 'Hungary', 'id' => '348', 'iso_alpha2' => 'HU', 'iso_alpha3' => 'HUN']);
        Country::create(['region_id' => '151', 'name' => 'Poland', 'id' => '616', 'iso_alpha2' => 'PL', 'iso_alpha3' => 'POL']);
        Country::create(['region_id' => '151', 'name' => 'Republic of Moldova', 'id' => '498', 'iso_alpha2' => 'MD', 'iso_alpha3' => 'MDA']);
        Country::create(['region_id' => '151', 'name' => 'Romania', 'id' => '642', 'iso_alpha2' => 'RO', 'iso_alpha3' => 'ROU']);
        Country::create(['region_id' => '151', 'name' => 'Russian Federation', 'id' => '643', 'iso_alpha2' => 'RU', 'iso_alpha3' => 'RUS']);
        Country::create(['region_id' => '151', 'name' => 'Slovakia', 'id' => '703', 'iso_alpha2' => 'SK', 'iso_alpha3' => 'SVK']);
        Country::create(['region_id' => '151', 'name' => 'Ukraine', 'id' => '804', 'iso_alpha2' => 'UA', 'iso_alpha3' => 'UKR']);
        Country::create(['region_id' => '154', 'name' => 'Åland Islands', 'id' => '248', 'iso_alpha2' => 'AX', 'iso_alpha3' => 'ALA']);
        Country::create(['region_id' => '830', 'name' => 'Guernsey', 'id' => '831', 'iso_alpha2' => 'GG', 'iso_alpha3' => 'GGY']);
        Country::create(['region_id' => '830', 'name' => 'Jersey', 'id' => '832', 'iso_alpha2' => 'JE', 'iso_alpha3' => 'JEY']);
        Country::create(['region_id' => '830', 'name' => 'Sark', 'id' => '680', 'iso_alpha2' => '', 'iso_alpha3' => '']);
        Country::create(['region_id' => '154', 'name' => 'Denmark', 'id' => '208', 'iso_alpha2' => 'DK', 'iso_alpha3' => 'DNK']);
        Country::create(['region_id' => '154', 'name' => 'Estonia', 'id' => '233', 'iso_alpha2' => 'EE', 'iso_alpha3' => 'EST']);
        Country::create(['region_id' => '154', 'name' => 'Faroe Islands', 'id' => '234', 'iso_alpha2' => 'FO', 'iso_alpha3' => 'FRO']);
        Country::create(['region_id' => '154', 'name' => 'Finland', 'id' => '246', 'iso_alpha2' => 'FI', 'iso_alpha3' => 'FIN']);
        Country::create(['region_id' => '154', 'name' => 'Iceland', 'id' => '352', 'iso_alpha2' => 'IS', 'iso_alpha3' => 'ISL']);
        Country::create(['region_id' => '154', 'name' => 'Ireland', 'id' => '372', 'iso_alpha2' => 'IE', 'iso_alpha3' => 'IRL']);
        Country::create(['region_id' => '154', 'name' => 'Isle of Man', 'id' => '833', 'iso_alpha2' => 'IM', 'iso_alpha3' => 'IMN']);
        Country::create(['region_id' => '154', 'name' => 'Latvia', 'id' => '428', 'iso_alpha2' => 'LV', 'iso_alpha3' => 'LVA']);
        Country::create(['region_id' => '154', 'name' => 'Lithuania', 'id' => '440', 'iso_alpha2' => 'LT', 'iso_alpha3' => 'LTU']);
        Country::create(['region_id' => '154', 'name' => 'Norway', 'id' => '578', 'iso_alpha2' => 'NO', 'iso_alpha3' => 'NOR']);
        Country::create(['region_id' => '154', 'name' => 'Svalbard and Jan Mayen Islands', 'id' => '744', 'iso_alpha2' => 'SJ', 'iso_alpha3' => 'SJM']);
        Country::create(['region_id' => '154', 'name' => 'Sweden', 'id' => '752', 'iso_alpha2' => 'SE', 'iso_alpha3' => 'SWE']);
        Country::create(['region_id' => '154', 'name' => 'United Kingdom of Great Britain and Northern Ireland', 'id' => '826', 'iso_alpha2' => 'GB', 'iso_alpha3' => 'GBR']);
        Country::create(['region_id' => '039', 'name' => 'Albania', 'id' => '008', 'iso_alpha2' => 'AL', 'iso_alpha3' => 'ALB']);
        Country::create(['region_id' => '039', 'name' => 'Andorra', 'id' => '020', 'iso_alpha2' => 'AD', 'iso_alpha3' => 'AND']);
        Country::create(['region_id' => '039', 'name' => 'Bosnia and Herzegovina', 'id' => '070', 'iso_alpha2' => 'BA', 'iso_alpha3' => 'BIH']);
        Country::create(['region_id' => '039', 'name' => 'Croatia', 'id' => '191', 'iso_alpha2' => 'HR', 'iso_alpha3' => 'HRV']);
        Country::create(['region_id' => '039', 'name' => 'Gibraltar', 'id' => '292', 'iso_alpha2' => 'GI', 'iso_alpha3' => 'GIB']);
        Country::create(['region_id' => '039', 'name' => 'Greece', 'id' => '300', 'iso_alpha2' => 'GR', 'iso_alpha3' => 'GRC']);
        Country::create(['region_id' => '039', 'name' => 'Holy See', 'id' => '336', 'iso_alpha2' => 'VA', 'iso_alpha3' => 'VAT']);
        Country::create(['region_id' => '039', 'name' => 'Italy', 'id' => '380', 'iso_alpha2' => 'IT', 'iso_alpha3' => 'ITA']);
        Country::create(['region_id' => '039', 'name' => 'Malta', 'id' => '470', 'iso_alpha2' => 'MT', 'iso_alpha3' => 'MLT']);
        Country::create(['region_id' => '039', 'name' => 'Montenegro', 'id' => '499', 'iso_alpha2' => 'ME', 'iso_alpha3' => 'MNE']);
        Country::create(['region_id' => '039', 'name' => 'North Macedonia', 'id' => '807', 'iso_alpha2' => 'MK', 'iso_alpha3' => 'MKD']);
        Country::create(['region_id' => '039', 'name' => 'Portugal', 'id' => '620', 'iso_alpha2' => 'PT', 'iso_alpha3' => 'PRT']);
        Country::create(['region_id' => '039', 'name' => 'San Marino', 'id' => '674', 'iso_alpha2' => 'SM', 'iso_alpha3' => 'SMR']);
        Country::create(['region_id' => '039', 'name' => 'Serbia', 'id' => '688', 'iso_alpha2' => 'RS', 'iso_alpha3' => 'SRB']);
        Country::create(['region_id' => '039', 'name' => 'Slovenia', 'id' => '705', 'iso_alpha2' => 'SI', 'iso_alpha3' => 'SVN']);
        Country::create(['region_id' => '039', 'name' => 'Spain', 'id' => '724', 'iso_alpha2' => 'ES', 'iso_alpha3' => 'ESP']);
        Country::create(['region_id' => '155', 'name' => 'Austria', 'id' => '040', 'iso_alpha2' => 'AT', 'iso_alpha3' => 'AUT']);
        Country::create(['region_id' => '155', 'name' => 'Belgium', 'id' => '056', 'iso_alpha2' => 'BE', 'iso_alpha3' => 'BEL']);
        Country::create(['region_id' => '155', 'name' => 'France', 'id' => '250', 'iso_alpha2' => 'FR', 'iso_alpha3' => 'FRA']);
        Country::create(['region_id' => '155', 'name' => 'Germany', 'id' => '276', 'iso_alpha2' => 'DE', 'iso_alpha3' => 'DEU']);
        Country::create(['region_id' => '155', 'name' => 'Liechtenstein', 'id' => '438', 'iso_alpha2' => 'LI', 'iso_alpha3' => 'LIE']);
        Country::create(['region_id' => '155', 'name' => 'Luxembourg', 'id' => '442', 'iso_alpha2' => 'LU', 'iso_alpha3' => 'LUX']);
        Country::create(['region_id' => '155', 'name' => 'Monaco', 'id' => '492', 'iso_alpha2' => 'MC', 'iso_alpha3' => 'MCO']);
        Country::create(['region_id' => '155', 'name' => 'Netherlands', 'id' => '528', 'iso_alpha2' => 'NL', 'iso_alpha3' => 'NLD']);
        Country::create(['region_id' => '155', 'name' => 'Switzerland', 'id' => '756', 'iso_alpha2' => 'CH', 'iso_alpha3' => 'CHE']);
        Country::create(['region_id' => '053', 'name' => 'Australia', 'id' => '036', 'iso_alpha2' => 'AU', 'iso_alpha3' => 'AUS']);
        Country::create(['region_id' => '053', 'name' => 'Christmas Island', 'id' => '162', 'iso_alpha2' => 'CX', 'iso_alpha3' => 'CXR']);
        Country::create(['region_id' => '053', 'name' => 'Cocos(Keeling) Islands', 'id' => '166', 'iso_alpha2' => 'CC', 'iso_alpha3' => 'CCK']);
        Country::create(['region_id' => '053', 'name' => 'Heard Island and McDonald Islands', 'id' => '334', 'iso_alpha2' => 'HM', 'iso_alpha3' => 'HMD']);
        Country::create(['region_id' => '053', 'name' => 'new Zealand', 'id' => '554', 'iso_alpha2' => 'NZ', 'iso_alpha3' => 'NZL']);
        Country::create(['region_id' => '053', 'name' => 'Norfolk Island', 'id' => '574', 'iso_alpha2' => 'NF', 'iso_alpha3' => 'NFK']);
        Country::create(['region_id' => '054', 'name' => 'Fiji', 'id' => '242', 'iso_alpha2' => 'FJ', 'iso_alpha3' => 'FJI']);
        Country::create(['region_id' => '054', 'name' => 'new Caledonia', 'id' => '540', 'iso_alpha2' => 'NC', 'iso_alpha3' => 'NCL']);
        Country::create(['region_id' => '054', 'name' => 'Papua new Guinea', 'id' => '598', 'iso_alpha2' => 'PG', 'iso_alpha3' => 'PNG']);
        Country::create(['region_id' => '054', 'name' => 'Solomon Islands', 'id' => '090', 'iso_alpha2' => 'SB', 'iso_alpha3' => 'SLB']);
        Country::create(['region_id' => '054', 'name' => 'Vanuatu', 'id' => '548', 'iso_alpha2' => 'VU', 'iso_alpha3' => 'VUT']);
        Country::create(['region_id' => '057', 'name' => 'Guam', 'id' => '316', 'iso_alpha2' => 'GU', 'iso_alpha3' => 'GUM']);
        Country::create(['region_id' => '057', 'name' => 'Kiribati', 'id' => '296', 'iso_alpha2' => 'KI', 'iso_alpha3' => 'KIR']);
        Country::create(['region_id' => '057', 'name' => 'Marshall Islands', 'id' => '584', 'iso_alpha2' => 'MH', 'iso_alpha3' => 'MHL']);
        Country::create(['region_id' => '057', 'name' => 'Micronesia(Federated States of)', 'id' => '583', 'iso_alpha2' => 'FM', 'iso_alpha3' => 'FSM']);
        Country::create(['region_id' => '057', 'name' => 'Nauru', 'id' => '520', 'iso_alpha2' => 'NR', 'iso_alpha3' => 'NRU']);
        Country::create(['region_id' => '057', 'name' => 'Northern Mariana Islands', 'id' => '580', 'iso_alpha2' => 'MP', 'iso_alpha3' => 'MNP']);
        Country::create(['region_id' => '057', 'name' => 'Palau', 'id' => '585', 'iso_alpha2' => 'PW', 'iso_alpha3' => 'PLW']);
        Country::create(['region_id' => '057', 'name' => 'United States Minor Outlying Islands', 'id' => '581', 'iso_alpha2' => 'UM', 'iso_alpha3' => 'UMI']);
        Country::create(['region_id' => '061', 'name' => 'American Samoa', 'id' => '016', 'iso_alpha2' => 'as', 'iso_alpha3' => 'ASM']);
        Country::create(['region_id' => '061', 'name' => 'Cook Islands', 'id' => '184', 'iso_alpha2' => 'CK', 'iso_alpha3' => 'COK']);
        Country::create(['region_id' => '061', 'name' => 'French Polynesia', 'id' => '258', 'iso_alpha2' => 'PF', 'iso_alpha3' => 'PYF']);
        Country::create(['region_id' => '061', 'name' => 'Niue', 'id' => '570', 'iso_alpha2' => 'NU', 'iso_alpha3' => 'NIU']);
        Country::create(['region_id' => '061', 'name' => 'Pitcairn', 'id' => '612', 'iso_alpha2' => 'PN', 'iso_alpha3' => 'PCN']);
        Country::create(['region_id' => '061', 'name' => 'Samoa', 'id' => '882', 'iso_alpha2' => 'WS', 'iso_alpha3' => 'WSM']);
        Country::create(['region_id' => '061', 'name' => 'Tokelau', 'id' => '772', 'iso_alpha2' => 'TK', 'iso_alpha3' => 'TKL']);
        Country::create(['region_id' => '061', 'name' => 'Tonga', 'id' => '776', 'iso_alpha2' => 'TO', 'iso_alpha3' => 'TON']);
        Country::create(['region_id' => '061', 'name' => 'Tuvalu', 'id' => '798', 'iso_alpha2' => 'TV', 'iso_alpha3' => 'TUV']);
        Country::create(['region_id' => '061', 'name' => 'Wallis and Futuna Islands', 'id' => '876', 'iso_alpha2' => 'WF', 'iso_alpha3' => 'WLF']);
    }
}
