<?php

namespace Database\Seeders\Prep;

use App\Models\Reference\Currency;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Currency::create(['id' => 'AED', 'name' => 'UAE Dirham']);
        Currency::create(['id' => 'AFN', 'name' => 'Afghani']);
        Currency::create(['id' => 'ALL', 'name' => 'Lek']);
        Currency::create(['id' => 'AMD', 'name' => 'Armenian Dram']);
        Currency::create(['id' => 'ANG', 'name' => 'Netherlands Antillean Guilder']);
        Currency::create(['id' => 'AOA', 'name' => 'Kwanza']);
        Currency::create(['id' => 'ARS', 'name' => 'Argentine Peso']);
        Currency::create(['id' => 'AUD', 'name' => 'Australian Dollar']);
        Currency::create(['id' => 'AWG', 'name' => 'Aruban Florin']);
        Currency::create(['id' => 'AZN', 'name' => 'Azerbaijanian Manat']);
        Currency::create(['id' => 'BAM', 'name' => 'Convertible Mark']);
        Currency::create(['id' => 'BBD', 'name' => 'Barbados Dollar']);
        Currency::create(['id' => 'BDT', 'name' => 'Taka']);
        Currency::create(['id' => 'BGN', 'name' => 'Bulgarian Lev']);
        Currency::create(['id' => 'BHD', 'name' => 'Bahraini Dinar']);
        Currency::create(['id' => 'BIF', 'name' => 'Burundi Franc']);
        Currency::create(['id' => 'BMD', 'name' => 'Bermudian Dollar']);
        Currency::create(['id' => 'BND', 'name' => 'Brunei Dollar']);
        Currency::create(['id' => 'BOB', 'name' => 'Boliviano']);
        Currency::create(['id' => 'BOV', 'name' => 'Mvdol']);
        Currency::create(['id' => 'BRL', 'name' => 'Brazilian Real']);
        Currency::create(['id' => 'BSD', 'name' => 'Bahamian Dollar']);
        Currency::create(['id' => 'BTN', 'name' => 'Ngultrum']);
        Currency::create(['id' => 'BWP', 'name' => 'Pula']);
        Currency::create(['id' => 'BYN', 'name' => 'Belarussian Ruble']);
        Currency::create(['id' => 'BZD', 'name' => 'Belize Dollar']);
        Currency::create(['id' => 'CAD', 'name' => 'Canadian Dollar']);
        Currency::create(['id' => 'CDF', 'name' => 'Congolese Franc']);
        Currency::create(['id' => 'CHE', 'name' => 'WIR Euro']);
        Currency::create(['id' => 'CHF', 'name' => 'Swiss Franc']);
        Currency::create(['id' => 'CHW', 'name' => 'WIR Franc']);
        Currency::create(['id' => 'CLF', 'name' => 'Unidad de Fomento']);
        Currency::create(['id' => 'CLP', 'name' => 'Chilean Peso']);
        Currency::create(['id' => 'CNY', 'name' => 'Chinese Yuan']);
        Currency::create(['id' => 'COP', 'name' => 'Colombian Peso']);
        Currency::create(['id' => 'COU', 'name' => 'Unidad de Valor Real']);
        Currency::create(['id' => 'CRC', 'name' => 'Costa Rican Colon']);
        Currency::create(['id' => 'CUC', 'name' => 'Peso Convertible']);
        Currency::create(['id' => 'CUP', 'name' => 'Cuban Peso']);
        Currency::create(['id' => 'CVE', 'name' => 'Cabo Verde Escudo']);
        Currency::create(['id' => 'CZK', 'name' => 'Czech Koruna']);
        Currency::create(['id' => 'DJF', 'name' => 'Djibouti Franc']);
        Currency::create(['id' => 'DKK', 'name' => 'Danish Krone']);
        Currency::create(['id' => 'DOP', 'name' => 'Dominican Peso']);
        Currency::create(['id' => 'DZD', 'name' => 'Algerian Dinar']);
        Currency::create(['id' => 'EGP', 'name' => 'Egyptian Pound']);
        Currency::create(['id' => 'ERN', 'name' => 'Nakfa']);
        Currency::create(['id' => 'ETB', 'name' => 'Ethiopian Birr']);
        Currency::create(['id' => 'EUR', 'name' => 'Euro']);
        Currency::create(['id' => 'FJD', 'name' => 'Fiji Dollar']);
        Currency::create(['id' => 'FKP', 'name' => 'Falkland Islands Pound']);
        Currency::create(['id' => 'GBP', 'name' => 'Pound Sterling']);
        Currency::create(['id' => 'GEL', 'name' => 'Lari']);
        Currency::create(['id' => 'GHS', 'name' => 'Ghana Cedi']);
        Currency::create(['id' => 'GIP', 'name' => 'Gibraltar Pound']);
        Currency::create(['id' => 'GMD', 'name' => 'Dalasi']);
        Currency::create(['id' => 'GNF', 'name' => 'Guinea Franc']);
        Currency::create(['id' => 'GTQ', 'name' => 'Quetzal']);
        Currency::create(['id' => 'GYD', 'name' => 'Guyana Dollar']);
        Currency::create(['id' => 'HKD', 'name' => 'Hong Kong Dollar']);
        Currency::create(['id' => 'HNL', 'name' => 'Lempira']);
        Currency::create(['id' => 'HTG', 'name' => 'Gourde']);
        Currency::create(['id' => 'HUF', 'name' => 'Forint']);
        Currency::create(['id' => 'IDR', 'name' => 'Rupiah']);
        Currency::create(['id' => 'ILS', 'name' => 'New Israeli Sheqel']);
        Currency::create(['id' => 'INR', 'name' => 'Indian Rupee']);
        Currency::create(['id' => 'IQD', 'name' => 'Iraqi Dinar']);
        Currency::create(['id' => 'IRR', 'name' => 'Iranian Rial']);
        Currency::create(['id' => 'ISK', 'name' => 'Iceland Krona']);
        Currency::create(['id' => 'JMD', 'name' => 'Jamaican Dollar']);
        Currency::create(['id' => 'JOD', 'name' => 'Jordanian Dinar']);
        Currency::create(['id' => 'JPY', 'name' => 'Yen']);
        Currency::create(['id' => 'KES', 'name' => 'Kenyan Shilling']);
        Currency::create(['id' => 'KGS', 'name' => 'Som']);
        Currency::create(['id' => 'KHR', 'name' => 'Riel']);
        Currency::create(['id' => 'KMF', 'name' => 'Comoro Franc']);
        Currency::create(['id' => 'KPW', 'name' => 'North Korean Won']);
        Currency::create(['id' => 'KRW', 'name' => 'Won']);
        Currency::create(['id' => 'KWD', 'name' => 'Kuwaiti Dinar']);
        Currency::create(['id' => 'KYD', 'name' => 'Cayman Islands Dollar']);
        Currency::create(['id' => 'KZT', 'name' => 'Tenge']);
        Currency::create(['id' => 'LAK', 'name' => 'Kip']);
        Currency::create(['id' => 'LBP', 'name' => 'Lebanese Pound']);
        Currency::create(['id' => 'LKR', 'name' => 'Sri Lanka Rupee']);
        Currency::create(['id' => 'LRD', 'name' => 'Liberian Dollar']);
        Currency::create(['id' => 'LSL', 'name' => 'Loti']);
        Currency::create(['id' => 'LYD', 'name' => 'Libyan Dinar']);
        Currency::create(['id' => 'MAD', 'name' => 'Moroccan Dirham']);
        Currency::create(['id' => 'MDL', 'name' => 'Moldovan Leu']);
        Currency::create(['id' => 'MGA', 'name' => 'Malagasy Ariary']);
        Currency::create(['id' => 'MKD', 'name' => 'Denar']);
        Currency::create(['id' => 'MMK', 'name' => 'Kyat']);
        Currency::create(['id' => 'MNT', 'name' => 'Tugrik']);
        Currency::create(['id' => 'MOP', 'name' => 'Pataca']);
        Currency::create(['id' => 'MRU', 'name' => 'Ouguiya']);
        Currency::create(['id' => 'MUR', 'name' => 'Mauritius Rupee']);
        Currency::create(['id' => 'MVR', 'name' => 'Rufiyaa']);
        Currency::create(['id' => 'MWK', 'name' => 'Kwacha']);
        Currency::create(['id' => 'MXN', 'name' => 'Mexican Peso']);
        Currency::create(['id' => 'MXV', 'name' => 'Mexican Unidad de Inversion (UDI)']);
        Currency::create(['id' => 'MYR', 'name' => 'Malaysian Ringgit']);
        Currency::create(['id' => 'MZN', 'name' => 'Mozambique Metical']);
        Currency::create(['id' => 'NAD', 'name' => 'Namibia Dollar']);
        Currency::create(['id' => 'NGN', 'name' => 'Naira']);
        Currency::create(['id' => 'NIO', 'name' => 'Cordoba Oro']);
        Currency::create(['id' => 'NOK', 'name' => 'Norwegian Krone']);
        Currency::create(['id' => 'NPR', 'name' => 'Nepalese Rupee']);
        Currency::create(['id' => 'NZD', 'name' => 'new Zealand Dollar']);
        Currency::create(['id' => 'OMR', 'name' => 'Rial Omani']);
        Currency::create(['id' => 'PAB', 'name' => 'Balboa']);
        Currency::create(['id' => 'PEN', 'name' => 'Nuevo Sol']);
        Currency::create(['id' => 'PGK', 'name' => 'Kina']);
        Currency::create(['id' => 'PHP', 'name' => 'Philippine Peso']);
        Currency::create(['id' => 'PKR', 'name' => 'Pakistan Rupee']);
        Currency::create(['id' => 'PLN', 'name' => 'Zloty']);
        Currency::create(['id' => 'PYG', 'name' => 'Guarani']);
        Currency::create(['id' => 'QAR', 'name' => 'Qatari Rial']);
        Currency::create(['id' => 'RON', 'name' => 'Romanian Leu']);
        Currency::create(['id' => 'RSD', 'name' => 'Serbian Dinar']);
        Currency::create(['id' => 'RUB', 'name' => 'Russian Ruble']);
        Currency::create(['id' => 'RWF', 'name' => 'Rwanda Franc']);
        Currency::create(['id' => 'SAR', 'name' => 'Saudi Riyal']);
        Currency::create(['id' => 'SBD', 'name' => 'Solomon Islands Dollar']);
        Currency::create(['id' => 'SCR', 'name' => 'Seychelles Rupee']);
        Currency::create(['id' => 'SDG', 'name' => 'Sudanese Pound']);
        Currency::create(['id' => 'SEK', 'name' => 'Swedish Krona']);
        Currency::create(['id' => 'SGD', 'name' => 'Singapore Dollar']);
        Currency::create(['id' => 'SHP', 'name' => 'Saint Helena Pound']);
        Currency::create(['id' => 'SLE', 'name' => 'Leone']);
        Currency::create(['id' => 'SOM', 'name' => 'Kyrgyz Som']);
        Currency::create(['id' => 'SOS', 'name' => 'Somali Shilling']);
        Currency::create(['id' => 'SRD', 'name' => 'Surinam Dollar']);
        Currency::create(['id' => 'SSP', 'name' => 'South Sudanese Pound']);
        Currency::create(['id' => 'STN', 'name' => 'Dobra']);
        Currency::create(['id' => 'SVC', 'name' => 'El Salvador Colon']);
        Currency::create(['id' => 'SYP', 'name' => 'Syrian Pound']);
        Currency::create(['id' => 'SZL', 'name' => 'Lilangeni']);
        Currency::create(['id' => 'THB', 'name' => 'Baht']);
        Currency::create(['id' => 'TJS', 'name' => 'Somoni']);
        Currency::create(['id' => 'TMT', 'name' => 'Turkmenistan New Manat']);
        Currency::create(['id' => 'TND', 'name' => 'Tunisian Dinar']);
        Currency::create(['id' => 'TOP', 'name' => 'Pa’anga']);
        Currency::create(['id' => 'TRY', 'name' => 'Turkish Lira']);
        Currency::create(['id' => 'TTD', 'name' => 'Trinidad and Tobago Dollar']);
        Currency::create(['id' => 'TWD', 'name' => 'new Taiwan Dollar']);
        Currency::create(['id' => 'TZS', 'name' => 'Tanzanian Shilling']);
        Currency::create(['id' => 'UAH', 'name' => 'Hryvnia']);
        Currency::create(['id' => 'UGX', 'name' => 'Uganda Shilling']);
        Currency::create(['id' => 'USD', 'name' => 'US Dollar']);
        Currency::create(['id' => 'USN', 'name' => 'US Dollar(Next day)']);
        Currency::create(['id' => 'UYI', 'name' => 'Uruguay Peso en Unidades Indexadas ()']);
        Currency::create(['id' => 'UYU', 'name' => 'Peso Uruguayo']);
        Currency::create(['id' => 'UZS', 'name' => 'Uzbekistan Sum']);
        Currency::create(['id' => 'VEF', 'name' => 'bolivar fuerte']);
        Currency::create(['id' => 'VES', 'name' => 'sovereign bolivar']);
        Currency::create(['id' => 'VND', 'name' => 'Dong']);
        Currency::create(['id' => 'VUV', 'name' => 'Vatu']);
        Currency::create(['id' => 'WST', 'name' => 'Tala']);
        Currency::create(['id' => 'XAF', 'name' => 'Central African CFA Franc']);
        Currency::create(['id' => 'XCD', 'name' => 'East Caribbean Dollar']);
        Currency::create(['id' => 'XDR', 'name' => 'SDR (Special Drawing Right)']);
        Currency::create(['id' => 'XOF', 'name' => 'West African CFA Franc']);
        Currency::create(['id' => 'XPF', 'name' => 'CFP Franc']);
        Currency::create(['id' => 'XSU', 'name' => 'Sucre']);
        Currency::create(['id' => 'XUA', 'name' => 'ADB Unit of Account']);
        Currency::create(['id' => 'YER', 'name' => 'Yemeni Rial']);
        Currency::create(['id' => 'ZAR', 'name' => 'Rand']);
        Currency::create(['id' => 'ZMW', 'name' => 'Zambian Kwacha']);
        Currency::create(['id' => 'ZWL', 'name' => 'Zimbabwe Dollar']);

    }
}
