<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ChoiceListsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('choice_lists')->delete();
        
        \DB::table('choice_lists')->insert(array (
            0 => 
            array (
                'id' => 1,
                'xlsform_module_version_id' => 1,
                'list_name' => 'language',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:46',
                'updated_at' => '2025-02-20 15:40:46',
            ),
            1 => 
            array (
                'id' => 2,
                'xlsform_module_version_id' => 1,
                'list_name' => 'district',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:46',
                'updated_at' => '2025-02-20 15:40:46',
            ),
            2 => 
            array (
                'id' => 3,
                'xlsform_module_version_id' => 1,
                'list_name' => 'sub_district',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:46',
                'updated_at' => '2025-02-20 15:40:46',
            ),
            3 => 
            array (
                'id' => 4,
                'xlsform_module_version_id' => 1,
                'list_name' => 'village',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:46',
                'updated_at' => '2025-02-20 15:40:46',
            ),
            4 => 
            array (
                'id' => 5,
                'xlsform_module_version_id' => 1,
                'list_name' => 'farm',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:46',
                'updated_at' => '2025-02-20 15:40:46',
            ),
            5 => 
            array (
                'id' => 6,
                'xlsform_module_version_id' => 1,
                'list_name' => 'yn',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:46',
                'updated_at' => '2025-02-20 15:40:47',
            ),
            6 => 
            array (
                'id' => 11,
                'xlsform_module_version_id' => 1,
                'list_name' => 'relationship',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:47',
                'updated_at' => '2025-02-20 15:40:47',
            ),
            7 => 
            array (
                'id' => 12,
                'xlsform_module_version_id' => 1,
                'list_name' => 'relationship_dm',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:47',
                'updated_at' => '2025-02-20 15:40:47',
            ),
            8 => 
            array (
                'id' => 13,
                'xlsform_module_version_id' => 1,
                'list_name' => 'gender',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:47',
                'updated_at' => '2025-02-20 15:40:47',
            ),
            9 => 
            array (
                'id' => 14,
                'xlsform_module_version_id' => 1,
                'list_name' => 'marital_status',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:47',
                'updated_at' => '2025-02-20 15:40:47',
            ),
            10 => 
            array (
                'id' => 15,
                'xlsform_module_version_id' => 1,
                'list_name' => 'read_write',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:47',
                'updated_at' => '2025-02-20 15:40:47',
            ),
            11 => 
            array (
                'id' => 16,
                'xlsform_module_version_id' => 1,
                'list_name' => 'education',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:47',
                'updated_at' => '2025-02-20 15:40:47',
            ),
            12 => 
            array (
                'id' => 17,
                'xlsform_module_version_id' => 1,
                'list_name' => 'grade',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:47',
                'updated_at' => '2025-02-20 15:40:47',
            ),
            13 => 
            array (
                'id' => 18,
                'xlsform_module_version_id' => 1,
                'list_name' => 'occupation',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:47',
                'updated_at' => '2025-02-20 15:40:47',
            ),
            14 => 
            array (
                'id' => 23,
                'xlsform_module_version_id' => 1,
                'list_name' => 'yn_dk',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:47',
                'updated_at' => '2025-02-20 15:40:47',
            ),
            15 => 
            array (
                'id' => 27,
                'xlsform_module_version_id' => 2,
                'list_name' => 'yn_dk',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:51',
                'updated_at' => '2025-02-20 15:40:51',
            ),
            16 => 
            array (
                'id' => 28,
                'xlsform_module_version_id' => 2,
                'list_name' => 'ae_understand',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:51',
                'updated_at' => '2025-02-20 15:40:51',
            ),
            17 => 
            array (
                'id' => 29,
                'xlsform_module_version_id' => 2,
                'list_name' => 'agree',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:51',
                'updated_at' => '2025-02-20 15:40:51',
            ),
            18 => 
            array (
                'id' => 42,
                'xlsform_module_version_id' => 3,
                'list_name' => 'satisfaction',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:54',
                'updated_at' => '2025-02-20 15:40:54',
            ),
            19 => 
            array (
                'id' => 54,
                'xlsform_module_version_id' => 4,
                'list_name' => 'step_power',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:56',
                'updated_at' => '2025-02-20 15:40:57',
            ),
            20 => 
            array (
                'id' => 59,
                'xlsform_module_version_id' => 4,
                'list_name' => 'step_differ',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:40:57',
                'updated_at' => '2025-02-20 15:40:57',
            ),
            21 => 
            array (
                'id' => 62,
                'xlsform_module_version_id' => 6,
                'list_name' => 'participation',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:00',
                'updated_at' => '2025-02-20 15:41:00',
            ),
            22 => 
            array (
                'id' => 63,
                'xlsform_module_version_id' => 6,
                'list_name' => 'contribution',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:00',
                'updated_at' => '2025-02-20 15:41:00',
            ),
            23 => 
            array (
                'id' => 64,
                'xlsform_module_version_id' => 6,
                'list_name' => 'management',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:00',
                'updated_at' => '2025-02-20 15:41:00',
            ),
            24 => 
            array (
                'id' => 65,
                'xlsform_module_version_id' => 7,
                'list_name' => 'associations',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:02',
                'updated_at' => '2025-02-20 15:41:02',
            ),
            25 => 
            array (
                'id' => 66,
                'xlsform_module_version_id' => 7,
                'list_name' => 'effectiveness',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:02',
                'updated_at' => '2025-02-20 15:41:02',
            ),
            26 => 
            array (
                'id' => 67,
                'xlsform_module_version_id' => 8,
                'list_name' => 'area_unit',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:04',
                'updated_at' => '2025-02-20 15:41:04',
            ),
            27 => 
            array (
                'id' => 68,
                'xlsform_module_version_id' => 8,
                'list_name' => 'likelihood',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:04',
                'updated_at' => '2025-02-20 15:41:04',
            ),
            28 => 
            array (
                'id' => 69,
                'xlsform_module_version_id' => 9,
                'list_name' => 'shocks',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:05',
                'updated_at' => '2025-02-20 15:41:05',
            ),
            29 => 
            array (
                'id' => 70,
                'xlsform_module_version_id' => 9,
                'list_name' => 'coping_strategies',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:05',
                'updated_at' => '2025-02-20 15:41:05',
            ),
            30 => 
            array (
                'id' => 71,
                'xlsform_module_version_id' => 9,
                'list_name' => 'recovery',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:05',
                'updated_at' => '2025-02-20 15:41:05',
            ),
            31 => 
            array (
                'id' => 72,
                'xlsform_module_version_id' => 9,
                'list_name' => 'insurance',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:05',
                'updated_at' => '2025-02-20 15:41:05',
            ),
            32 => 
            array (
                'id' => 73,
                'xlsform_module_version_id' => 9,
                'list_name' => 'coverage',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:05',
                'updated_at' => '2025-02-20 15:41:05',
            ),
            33 => 
            array (
                'id' => 74,
                'xlsform_module_version_id' => 9,
                'list_name' => 'yn_dk',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:06',
                'updated_at' => '2025-02-20 15:41:06',
            ),
            34 => 
            array (
                'id' => 87,
                'xlsform_module_version_id' => 10,
                'list_name' => 'income_sources',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:08',
                'updated_at' => '2025-02-20 15:41:08',
            ),
            35 => 
            array (
                'id' => 88,
                'xlsform_module_version_id' => 10,
                'list_name' => 'sufficient_income',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:08',
                'updated_at' => '2025-02-20 15:41:08',
            ),
            36 => 
            array (
                'id' => 89,
                'xlsform_module_version_id' => 10,
                'list_name' => 'income_stability',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:08',
                'updated_at' => '2025-02-20 15:41:08',
            ),
            37 => 
            array (
                'id' => 90,
                'xlsform_module_version_id' => 10,
                'list_name' => 'yn_dk',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:08',
                'updated_at' => '2025-02-20 15:41:08',
            ),
            38 => 
            array (
                'id' => 91,
                'xlsform_module_version_id' => 12,
                'list_name' => 'credit_access',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:11',
                'updated_at' => '2025-02-20 15:41:11',
            ),
            39 => 
            array (
                'id' => 92,
                'xlsform_module_version_id' => 12,
                'list_name' => 'credit_source',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:11',
                'updated_at' => '2025-02-20 15:41:11',
            ),
            40 => 
            array (
                'id' => 93,
                'xlsform_module_version_id' => 12,
                'list_name' => 'investments',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:11',
                'updated_at' => '2025-02-20 15:41:11',
            ),
            41 => 
            array (
                'id' => 94,
                'xlsform_module_version_id' => 12,
                'list_name' => 'yn',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:11',
                'updated_at' => '2025-02-20 15:41:11',
            ),
            42 => 
            array (
                'id' => 95,
                'xlsform_module_version_id' => 12,
                'list_name' => 'debt_repay',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:11',
                'updated_at' => '2025-02-20 15:41:11',
            ),
            43 => 
            array (
                'id' => 96,
                'xlsform_module_version_id' => 13,
                'list_name' => 'yn',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:13',
                'updated_at' => '2025-02-20 15:41:14',
            ),
            44 => 
            array (
                'id' => 126,
                'xlsform_module_version_id' => 13,
                'list_name' => 'food_access',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:14',
                'updated_at' => '2025-02-20 15:41:14',
            ),
            45 => 
            array (
                'id' => 130,
                'xlsform_module_version_id' => 13,
                'list_name' => 'percent',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:14',
                'updated_at' => '2025-02-20 15:41:14',
            ),
            46 => 
            array (
                'id' => 131,
                'xlsform_module_version_id' => 13,
                'list_name' => 'meals',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:14',
                'updated_at' => '2025-02-20 15:41:14',
            ),
            47 => 
            array (
                'id' => 132,
                'xlsform_module_version_id' => 14,
                'list_name' => 'roof_material',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:16',
                'updated_at' => '2025-02-20 15:41:16',
            ),
            48 => 
            array (
                'id' => 133,
                'xlsform_module_version_id' => 14,
                'list_name' => 'wall_material',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:16',
                'updated_at' => '2025-02-20 15:41:16',
            ),
            49 => 
            array (
                'id' => 134,
                'xlsform_module_version_id' => 14,
                'list_name' => 'yn',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:16',
                'updated_at' => '2025-02-20 15:41:16',
            ),
            50 => 
            array (
                'id' => 140,
                'xlsform_module_version_id' => 14,
                'list_name' => 'distance',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:16',
                'updated_at' => '2025-02-20 15:41:17',
            ),
            51 => 
            array (
                'id' => 141,
                'xlsform_module_version_id' => 14,
                'list_name' => 'transport',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:16',
                'updated_at' => '2025-02-20 15:41:17',
            ),
            52 => 
            array (
                'id' => 156,
                'xlsform_module_version_id' => 15,
                'list_name' => 'percent_veg',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:19',
                'updated_at' => '2025-02-20 15:41:19',
            ),
            53 => 
            array (
                'id' => 166,
                'xlsform_module_version_id' => 15,
                'list_name' => 'diversity',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:19',
                'updated_at' => '2025-02-20 15:41:19',
            ),
            54 => 
            array (
                'id' => 173,
                'xlsform_module_version_id' => 15,
                'list_name' => 'diversity2',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:19',
                'updated_at' => '2025-02-20 15:41:19',
            ),
            55 => 
            array (
                'id' => 176,
                'xlsform_module_version_id' => 15,
                'list_name' => 'diversity3',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:19',
                'updated_at' => '2025-02-20 15:41:19',
            ),
            56 => 
            array (
                'id' => 177,
                'xlsform_module_version_id' => 15,
                'list_name' => 'diversity4',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:19',
                'updated_at' => '2025-02-20 15:41:19',
            ),
            57 => 
            array (
                'id' => 178,
                'xlsform_module_version_id' => 15,
                'list_name' => 'diversity5',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:19',
                'updated_at' => '2025-02-20 15:41:19',
            ),
            58 => 
            array (
                'id' => 179,
                'xlsform_module_version_id' => 16,
                'list_name' => 'farm_products',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:21',
                'updated_at' => '2025-02-20 15:41:21',
            ),
            59 => 
            array (
                'id' => 180,
                'xlsform_module_version_id' => 16,
                'list_name' => 'percent_produce',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:41:21',
                'updated_at' => '2025-02-20 15:42:02',
            ),
            60 => 
            array (
                'id' => 186,
                'xlsform_module_version_id' => 16,
                'list_name' => 'buyer',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:01',
                'updated_at' => '2025-02-20 15:42:02',
            ),
            61 => 
            array (
                'id' => 187,
                'xlsform_module_version_id' => 16,
                'list_name' => 'fair_price',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:01',
                'updated_at' => '2025-02-20 15:42:02',
            ),
            62 => 
            array (
                'id' => 230,
                'xlsform_module_version_id' => 17,
                'list_name' => 'farm_products',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:03',
                'updated_at' => '2025-02-20 15:42:04',
            ),
            63 => 
            array (
                'id' => 231,
                'xlsform_module_version_id' => 17,
                'list_name' => 'crop_activities',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:03',
                'updated_at' => '2025-02-20 15:42:04',
            ),
            64 => 
            array (
                'id' => 232,
                'xlsform_module_version_id' => 17,
                'list_name' => 'livestock_activities',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:03',
                'updated_at' => '2025-02-20 15:42:04',
            ),
            65 => 
            array (
                'id' => 233,
                'xlsform_module_version_id' => 17,
                'list_name' => 'fish_activities',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:03',
                'updated_at' => '2025-02-20 15:42:04',
            ),
            66 => 
            array (
                'id' => 234,
                'xlsform_module_version_id' => 17,
                'list_name' => 'tree_activities',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:04',
                'updated_at' => '2025-02-20 15:42:04',
            ),
            67 => 
            array (
                'id' => 235,
                'xlsform_module_version_id' => 17,
                'list_name' => 'honey_activities',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:04',
                'updated_at' => '2025-02-20 15:42:05',
            ),
            68 => 
            array (
                'id' => 236,
                'xlsform_module_version_id' => 17,
                'list_name' => 'seasons',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:04',
                'updated_at' => '2025-02-20 15:42:04',
            ),
            69 => 
            array (
                'id' => 237,
                'xlsform_module_version_id' => 17,
                'list_name' => 'months',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:04',
                'updated_at' => '2025-02-20 15:42:04',
            ),
            70 => 
            array (
                'id' => 244,
                'xlsform_module_version_id' => 17,
                'list_name' => 'labourers',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:04',
                'updated_at' => '2025-02-20 15:42:04',
            ),
            71 => 
            array (
                'id' => 245,
                'xlsform_module_version_id' => 17,
                'list_name' => 'labour_group',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:04',
                'updated_at' => '2025-02-20 15:42:04',
            ),
            72 => 
            array (
                'id' => 261,
                'xlsform_module_version_id' => 18,
                'list_name' => 'crops',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:06',
                'updated_at' => '2025-02-20 15:42:06',
            ),
            73 => 
            array (
                'id' => 262,
                'xlsform_module_version_id' => 18,
                'list_name' => 'practices',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:06',
                'updated_at' => '2025-02-20 15:42:06',
            ),
            74 => 
            array (
                'id' => 264,
                'xlsform_module_version_id' => 18,
                'list_name' => 'practices2',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:06',
                'updated_at' => '2025-02-20 15:42:06',
            ),
            75 => 
            array (
                'id' => 265,
                'xlsform_module_version_id' => 18,
                'list_name' => 'trees1',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:06',
                'updated_at' => '2025-02-20 15:42:06',
            ),
            76 => 
            array (
                'id' => 271,
                'xlsform_module_version_id' => 18,
                'list_name' => 'trees_num',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:06',
                'updated_at' => '2025-02-20 15:42:06',
            ),
            77 => 
            array (
                'id' => 274,
                'xlsform_module_version_id' => 18,
                'list_name' => 'tree_diversity',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:06',
                'updated_at' => '2025-02-20 15:42:07',
            ),
            78 => 
            array (
                'id' => 277,
                'xlsform_module_version_id' => 18,
                'list_name' => 'trees_arrg',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:07',
                'updated_at' => '2025-02-20 15:42:07',
            ),
            79 => 
            array (
                'id' => 280,
                'xlsform_module_version_id' => 18,
                'list_name' => 'yield_unit',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:07',
                'updated_at' => '2025-02-20 15:42:07',
            ),
            80 => 
            array (
                'id' => 281,
                'xlsform_module_version_id' => 18,
                'list_name' => 'crop_use',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:07',
                'updated_at' => '2025-02-20 15:42:07',
            ),
            81 => 
            array (
                'id' => 282,
                'xlsform_module_version_id' => 18,
                'list_name' => 'seed_source',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:07',
                'updated_at' => '2025-02-20 15:42:07',
            ),
            82 => 
            array (
                'id' => 283,
                'xlsform_module_version_id' => 18,
                'list_name' => 'seed_type',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:07',
                'updated_at' => '2025-02-20 15:42:07',
            ),
            83 => 
            array (
                'id' => 284,
                'xlsform_module_version_id' => 19,
                'list_name' => 'slope',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:08',
                'updated_at' => '2025-02-20 15:42:08',
            ),
            84 => 
            array (
                'id' => 285,
                'xlsform_module_version_id' => 19,
                'list_name' => 'erosion',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:08',
                'updated_at' => '2025-02-20 15:42:08',
            ),
            85 => 
            array (
                'id' => 286,
                'xlsform_module_version_id' => 19,
                'list_name' => 'fertility',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:08',
                'updated_at' => '2025-02-20 15:42:08',
            ),
            86 => 
            array (
                'id' => 287,
                'xlsform_module_version_id' => 19,
                'list_name' => 'sf_methods',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:08',
                'updated_at' => '2025-02-20 15:42:08',
            ),
            87 => 
            array (
                'id' => 288,
                'xlsform_module_version_id' => 19,
                'list_name' => 'fert_unit',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:08',
                'updated_at' => '2025-02-20 15:42:09',
            ),
            88 => 
            array (
                'id' => 289,
                'xlsform_module_version_id' => 19,
                'list_name' => 'manure_source',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:08',
                'updated_at' => '2025-02-20 15:42:08',
            ),
            89 => 
            array (
                'id' => 292,
                'xlsform_module_version_id' => 19,
                'list_name' => 'sf_practices',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:09',
                'updated_at' => '2025-02-20 15:42:09',
            ),
            90 => 
            array (
                'id' => 293,
                'xlsform_module_version_id' => 19,
                'list_name' => 'pd_methods',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:09',
                'updated_at' => '2025-02-20 15:42:09',
            ),
            91 => 
            array (
                'id' => 296,
                'xlsform_module_version_id' => 19,
                'list_name' => 'pd_practices',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:09',
                'updated_at' => '2025-02-20 15:42:09',
            ),
            92 => 
            array (
                'id' => 297,
                'xlsform_module_version_id' => 20,
                'list_name' => 'yn',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:10',
                'updated_at' => '2025-02-20 15:42:10',
            ),
            93 => 
            array (
                'id' => 298,
                'xlsform_module_version_id' => 21,
                'list_name' => 'livestock',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:11',
                'updated_at' => '2025-02-20 15:42:11',
            ),
            94 => 
            array (
                'id' => 299,
                'xlsform_module_version_id' => 21,
                'list_name' => 'livestock2',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:38',
                'updated_at' => '2025-02-20 15:42:38',
            ),
            95 => 
            array (
                'id' => 300,
                'xlsform_module_version_id' => 21,
                'list_name' => 'livestock_uses',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:38',
                'updated_at' => '2025-02-20 15:42:38',
            ),
            96 => 
            array (
                'id' => 301,
                'xlsform_module_version_id' => 21,
                'list_name' => 'livestock_unit',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:38',
                'updated_at' => '2025-02-20 15:42:38',
            ),
            97 => 
            array (
                'id' => 302,
                'xlsform_module_version_id' => 21,
                'list_name' => 'livestock_use_output',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:38',
                'updated_at' => '2025-02-20 15:42:38',
            ),
            98 => 
            array (
                'id' => 303,
                'xlsform_module_version_id' => 21,
                'list_name' => 'livestock_source',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:38',
                'updated_at' => '2025-02-20 15:42:38',
            ),
            99 => 
            array (
                'id' => 304,
                'xlsform_module_version_id' => 21,
                'list_name' => 'exotic_local',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:38',
                'updated_at' => '2025-02-20 15:42:38',
            ),
            100 => 
            array (
                'id' => 305,
                'xlsform_module_version_id' => 21,
                'list_name' => 'feed',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:38',
                'updated_at' => '2025-02-20 15:42:38',
            ),
            101 => 
            array (
                'id' => 306,
                'xlsform_module_version_id' => 21,
                'list_name' => 'yn',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:38',
                'updated_at' => '2025-02-20 15:42:38',
            ),
            102 => 
            array (
                'id' => 308,
                'xlsform_module_version_id' => 21,
                'list_name' => 'livestock_disease',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:38',
                'updated_at' => '2025-02-20 15:42:38',
            ),
            103 => 
            array (
                'id' => 309,
                'xlsform_module_version_id' => 21,
                'list_name' => 'disease_management',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:38',
                'updated_at' => '2025-02-20 15:42:38',
            ),
            104 => 
            array (
                'id' => 310,
                'xlsform_module_version_id' => 21,
                'list_name' => 'animal_health',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:38',
                'updated_at' => '2025-02-20 15:42:38',
            ),
            105 => 
            array (
                'id' => 311,
                'xlsform_module_version_id' => 21,
                'list_name' => 'animal_health_management',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:38',
                'updated_at' => '2025-02-20 15:42:38',
            ),
            106 => 
            array (
                'id' => 312,
                'xlsform_module_version_id' => 21,
                'list_name' => 'grazing_practices',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:38',
                'updated_at' => '2025-02-20 15:42:38',
            ),
            107 => 
            array (
                'id' => 313,
                'xlsform_module_version_id' => 22,
                'list_name' => 'fish_location',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:40',
                'updated_at' => '2025-02-20 15:42:40',
            ),
            108 => 
            array (
                'id' => 314,
                'xlsform_module_version_id' => 22,
                'list_name' => 'fish',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:40',
                'updated_at' => '2025-02-20 15:42:40',
            ),
            109 => 
            array (
                'id' => 315,
                'xlsform_module_version_id' => 22,
                'list_name' => 'fish2',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:40',
                'updated_at' => '2025-02-20 15:42:40',
            ),
            110 => 
            array (
                'id' => 316,
                'xlsform_module_version_id' => 22,
                'list_name' => 'fish_production_use',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:40',
                'updated_at' => '2025-02-20 15:42:40',
            ),
            111 => 
            array (
                'id' => 317,
                'xlsform_module_version_id' => 22,
                'list_name' => 'fish_unit',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:40',
                'updated_at' => '2025-02-20 15:42:40',
            ),
            112 => 
            array (
                'id' => 318,
                'xlsform_module_version_id' => 22,
                'list_name' => 'fish_use_output',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:40',
                'updated_at' => '2025-02-20 15:42:40',
            ),
            113 => 
            array (
                'id' => 319,
                'xlsform_module_version_id' => 22,
                'list_name' => 'spawn_source',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:40',
                'updated_at' => '2025-02-20 15:42:40',
            ),
            114 => 
            array (
                'id' => 320,
                'xlsform_module_version_id' => 22,
                'list_name' => 'fish_feed_source',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:40',
                'updated_at' => '2025-02-20 15:42:40',
            ),
            115 => 
            array (
                'id' => 321,
                'xlsform_module_version_id' => 22,
                'list_name' => 'fish_feed_type',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:40',
                'updated_at' => '2025-02-20 15:42:40',
            ),
            116 => 
            array (
                'id' => 322,
                'xlsform_module_version_id' => 22,
                'list_name' => 'fish_disease',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:40',
                'updated_at' => '2025-02-20 15:42:40',
            ),
            117 => 
            array (
                'id' => 323,
                'xlsform_module_version_id' => 22,
                'list_name' => 'fish_disease_management',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:40',
                'updated_at' => '2025-02-20 15:42:40',
            ),
            118 => 
            array (
                'id' => 324,
                'xlsform_module_version_id' => 22,
                'list_name' => 'fish_land_practice',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:40',
                'updated_at' => '2025-02-20 15:42:40',
            ),
            119 => 
            array (
                'id' => 325,
                'xlsform_module_version_id' => 23,
                'list_name' => 'relationship_actions',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:42',
                'updated_at' => '2025-02-20 15:42:42',
            ),
            120 => 
            array (
                'id' => 326,
                'xlsform_module_version_id' => 24,
                'list_name' => 'change',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:43',
                'updated_at' => '2025-02-20 15:42:43',
            ),
            121 => 
            array (
                'id' => 328,
                'xlsform_module_version_id' => 24,
                'list_name' => 'timing_change',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:43',
                'updated_at' => '2025-02-20 15:42:43',
            ),
            122 => 
            array (
                'id' => 329,
                'xlsform_module_version_id' => 24,
                'list_name' => 'yn_dk',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:43',
                'updated_at' => '2025-02-20 15:42:43',
            ),
            123 => 
            array (
                'id' => 331,
                'xlsform_module_version_id' => 25,
                'list_name' => 'yn',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:44',
                'updated_at' => '2025-02-20 15:42:44',
            ),
            124 => 
            array (
                'id' => 332,
                'xlsform_module_version_id' => 25,
                'list_name' => 'irrigation_methods',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:44',
                'updated_at' => '2025-02-20 15:42:44',
            ),
            125 => 
            array (
                'id' => 333,
                'xlsform_module_version_id' => 25,
                'list_name' => 'irrigation_source',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:44',
                'updated_at' => '2025-02-20 15:42:44',
            ),
            126 => 
            array (
                'id' => 334,
                'xlsform_module_version_id' => 25,
                'list_name' => 'seasons',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:44',
                'updated_at' => '2025-02-20 15:42:44',
            ),
            127 => 
            array (
                'id' => 335,
                'xlsform_module_version_id' => 25,
                'list_name' => 'months',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:44',
                'updated_at' => '2025-02-20 15:42:44',
            ),
            128 => 
            array (
                'id' => 337,
                'xlsform_module_version_id' => 25,
                'list_name' => 'rainwater',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:44',
                'updated_at' => '2025-02-20 15:42:44',
            ),
            129 => 
            array (
                'id' => 338,
                'xlsform_module_version_id' => 25,
                'list_name' => 'months2',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:45',
                'updated_at' => '2025-02-20 15:42:45',
            ),
            130 => 
            array (
                'id' => 341,
                'xlsform_module_version_id' => 26,
                'list_name' => 'irrig_energy',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:46',
                'updated_at' => '2025-02-20 15:42:46',
            ),
            131 => 
            array (
                'id' => 342,
                'xlsform_module_version_id' => 26,
                'list_name' => 'tillage_energy',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:46',
                'updated_at' => '2025-02-20 15:42:46',
            ),
            132 => 
            array (
                'id' => 343,
                'xlsform_module_version_id' => 26,
                'list_name' => 'cooking_energy',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:46',
                'updated_at' => '2025-02-20 15:42:46',
            ),
            133 => 
            array (
                'id' => 344,
                'xlsform_module_version_id' => 26,
                'list_name' => 'food_energy',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:46',
                'updated_at' => '2025-02-20 15:42:46',
            ),
            134 => 
            array (
                'id' => 345,
                'xlsform_module_version_id' => 26,
                'list_name' => 'energy_source',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:42:47',
                'updated_at' => '2025-02-20 15:42:47',
            ),
            135 => 
            array (
                'id' => 346,
                'xlsform_module_version_id' => 28,
                'list_name' => 'language',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:41',
                'updated_at' => '2025-02-20 15:51:41',
            ),
            136 => 
            array (
                'id' => 347,
                'xlsform_module_version_id' => 28,
                'list_name' => 'district',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:41',
                'updated_at' => '2025-02-20 15:51:41',
            ),
            137 => 
            array (
                'id' => 348,
                'xlsform_module_version_id' => 28,
                'list_name' => 'sub_district',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:41',
                'updated_at' => '2025-02-20 15:51:41',
            ),
            138 => 
            array (
                'id' => 349,
                'xlsform_module_version_id' => 28,
                'list_name' => 'village',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:41',
                'updated_at' => '2025-02-20 15:51:41',
            ),
            139 => 
            array (
                'id' => 350,
                'xlsform_module_version_id' => 28,
                'list_name' => 'farm',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:41',
                'updated_at' => '2025-02-20 15:51:41',
            ),
            140 => 
            array (
                'id' => 351,
                'xlsform_module_version_id' => 28,
                'list_name' => 'yn',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:41',
                'updated_at' => '2025-02-20 15:51:41',
            ),
            141 => 
            array (
                'id' => 355,
                'xlsform_module_version_id' => 28,
                'list_name' => 'relationship',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:41',
                'updated_at' => '2025-02-20 15:51:41',
            ),
            142 => 
            array (
                'id' => 356,
                'xlsform_module_version_id' => 28,
                'list_name' => 'relationship_dm',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:41',
                'updated_at' => '2025-02-20 15:51:41',
            ),
            143 => 
            array (
                'id' => 357,
                'xlsform_module_version_id' => 28,
                'list_name' => 'gender',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:41',
                'updated_at' => '2025-02-20 15:51:41',
            ),
            144 => 
            array (
                'id' => 358,
                'xlsform_module_version_id' => 28,
                'list_name' => 'data_type',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:41',
                'updated_at' => '2025-02-20 15:51:41',
            ),
            145 => 
            array (
                'id' => 359,
                'xlsform_module_version_id' => 29,
                'list_name' => 'tree_arrangement',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            146 => 
            array (
                'id' => 360,
                'xlsform_module_version_id' => 29,
                'list_name' => 'vegetation',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            147 => 
            array (
                'id' => 361,
                'xlsform_module_version_id' => 29,
                'list_name' => 'veg_area',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            148 => 
            array (
                'id' => 362,
                'xlsform_module_version_id' => 29,
                'list_name' => 'prod_system',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            149 => 
            array (
                'id' => 363,
                'xlsform_module_version_id' => 29,
                'list_name' => 'structure',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            150 => 
            array (
                'id' => 364,
                'xlsform_module_version_id' => 29,
                'list_name' => 'compaction',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            151 => 
            array (
                'id' => 365,
                'xlsform_module_version_id' => 29,
                'list_name' => 'depth',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            152 => 
            array (
                'id' => 366,
                'xlsform_module_version_id' => 29,
                'list_name' => 'residues',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            153 => 
            array (
                'id' => 367,
                'xlsform_module_version_id' => 29,
                'list_name' => 'colour',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            154 => 
            array (
                'id' => 368,
                'xlsform_module_version_id' => 29,
                'list_name' => 'moisture',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            155 => 
            array (
                'id' => 369,
                'xlsform_module_version_id' => 29,
                'list_name' => 'cover',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            156 => 
            array (
                'id' => 370,
                'xlsform_module_version_id' => 29,
                'list_name' => 'erosion',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            157 => 
            array (
                'id' => 371,
                'xlsform_module_version_id' => 29,
                'list_name' => 'invertebrate',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            158 => 
            array (
                'id' => 372,
                'xlsform_module_version_id' => 29,
                'list_name' => 'microbe',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            159 => 
            array (
                'id' => 373,
                'xlsform_module_version_id' => 29,
                'list_name' => 'appearance',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            160 => 
            array (
                'id' => 374,
                'xlsform_module_version_id' => 29,
                'list_name' => 'growth',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            161 => 
            array (
                'id' => 375,
                'xlsform_module_version_id' => 29,
                'list_name' => 'disease',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            162 => 
            array (
                'id' => 376,
                'xlsform_module_version_id' => 29,
                'list_name' => 'insect',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            163 => 
            array (
                'id' => 377,
                'xlsform_module_version_id' => 29,
                'list_name' => 'enemy',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            164 => 
            array (
                'id' => 378,
                'xlsform_module_version_id' => 29,
                'list_name' => 'weeds',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            165 => 
            array (
                'id' => 379,
                'xlsform_module_version_id' => 29,
                'list_name' => 'natural',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
            166 => 
            array (
                'id' => 380,
                'xlsform_module_version_id' => 29,
                'list_name' => 'management',
                'description' => NULL,
                'is_localisable' => 0,
                'is_dataset' => 0,
                'can_be_hidden_from_context' => 0,
                'has_custom_handling' => 0,
                'properties' => NULL,
                'created_at' => '2025-02-20 15:51:43',
                'updated_at' => '2025-02-20 15:51:43',
            ),
        ));
        
        
    }
}