<?php

namespace Database\Seeders\TestRealForms;

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('media')->delete();

        \DB::table('media')->insert(array (
            0 =>
            array (
                'id' => 1,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformTemplate',
                'model_id' => 1,
                'uuid' => '5214c24f-68fe-45c8-9aca-d6ce90f21b32',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household',
                'file_name' => 'HOLPA-Household.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 455387,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-16 17:27:28',
                'updated_at' => '2025-06-16 17:27:28',
            ),
            1 =>
            array (
                'id' => 2,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 1,
                'uuid' => '00e0c51b-1160-421e-9aa8-a04e22fcf288',
                'collection_name' => 'default',
                'name' => 'area_units',
                'file_name' => 'area_units.csv',
                'mime_type' => 'text/csv',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 252,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-16 17:28:51',
                'updated_at' => '2025-06-16 17:28:51',
            ),
            2 =>
            array (
                'id' => 3,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 2,
                'uuid' => '04206425-f2b6-4375-aef4-bb6478c58761',
                'collection_name' => 'default',
                'name' => 'fert_units',
                'file_name' => 'fert_units.csv',
                'mime_type' => 'text/plain',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 126,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-16 17:28:51',
                'updated_at' => '2025-06-16 17:28:51',
            ),
            3 =>
            array (
                'id' => 4,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 3,
                'uuid' => 'c2c2a73d-f083-4e21-ba6d-8e86d9eccffa',
                'collection_name' => 'default',
                'name' => 'yield_units',
                'file_name' => 'yield_units.csv',
                'mime_type' => 'text/csv',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 213,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-16 17:28:51',
                'updated_at' => '2025-06-16 17:28:51',
            ),
            4 =>
            array (
                'id' => 5,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformTemplate',
                'model_id' => 2,
                'uuid' => 'aa1a14a9-8c70-4882-806d-7e9c596a57bd',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork',
                'file_name' => 'HOLPA-Fieldwork.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 107698,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-16 17:29:14',
                'updated_at' => '2025-06-16 17:29:14',
            ),
            5 =>
            array (
                'id' => 6,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 4,
                'uuid' => '3c5674a3-f66d-4a8d-a5e9-d95d55a6f35f',
                'collection_name' => 'default',
                'name' => 'appearance',
                'file_name' => 'appearance.png',
                'mime_type' => 'image/png',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 1774,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-16 17:29:58',
                'updated_at' => '2025-06-16 17:29:58',
            ),
            6 =>
            array (
                'id' => 7,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 5,
                'uuid' => 'd4dfc9ed-e59c-46c3-b798-f76db8e370f1',
                'collection_name' => 'default',
                'name' => 'disease_incidence',
                'file_name' => 'disease_incidence.png',
                'mime_type' => 'image/jpeg',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 6417,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-16 17:29:58',
                'updated_at' => '2025-06-16 17:29:58',
            ),
            7 =>
            array (
                'id' => 8,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 6,
                'uuid' => '436dc476-55b8-4e24-8428-c499c62a8293',
                'collection_name' => 'default',
                'name' => 'insect_incidence',
                'file_name' => 'insect_incidence.png',
                'mime_type' => 'image/jpeg',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 10691,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-16 17:29:58',
                'updated_at' => '2025-06-16 17:29:58',
            ),
            8 =>
            array (
                'id' => 9,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 7,
                'uuid' => '777ae0fe-93a2-434a-bb7d-ba4163591b2c',
                'collection_name' => 'default',
                'name' => 'soil_sample',
                'file_name' => 'soil_sample.png',
                'mime_type' => 'image/jpeg',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 3105,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-16 17:29:58',
                'updated_at' => '2025-06-16 17:29:58',
            ),
            9 =>
            array (
                'id' => 10,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 1,
                'uuid' => '80cc0a46-4abd-4650-b7bc-6ff9cb3e9fd3',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Survey',
                'file_name' => 'HOLPA-Household-Survey.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 121226,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-16 17:30:50',
                'updated_at' => '2025-06-16 17:30:50',
            ),
            10 =>
            array (
                'id' => 11,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 2,
                'uuid' => '94dd7e89-c150-4970-874a-b5466b577c9f',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork Survey',
                'file_name' => 'HOLPA-Fieldwork-Survey.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 26866,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-16 17:31:09',
                'updated_at' => '2025-06-16 17:31:09',
            ),
            11 =>
            array (
                'id' => 12,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 4,
                'uuid' => '1d016e15-c807-4c00-8b98-24077a8fb86e',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork Survey',
                'file_name' => 'HOLPA-Fieldwork-Survey.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 26866,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-16 17:34:07',
                'updated_at' => '2025-06-16 17:34:07',
            ),
            12 =>
            array (
                'id' => 13,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 3,
                'uuid' => '1a9f3e1b-2b21-490c-b943-e009f7ba699a',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Survey',
                'file_name' => 'HOLPA-Household-Survey.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 121228,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-16 17:34:39',
                'updated_at' => '2025-06-16 17:34:39',
            ),
            13 =>
            array (
                'id' => 14,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 6,
                'uuid' => 'b838fc2d-b011-4296-b9e5-b6c4d57517e1',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork Survey',
                'file_name' => 'HOLPA-Fieldwork-Survey.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 26866,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-18 13:17:26',
                'updated_at' => '2025-06-18 13:17:26',
            ),
            14 =>
            array (
                'id' => 15,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 8,
                'uuid' => 'b595aef2-686d-453c-af48-6aa626b3bc15',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork Survey',
                'file_name' => 'HOLPA-Fieldwork-Survey.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 26865,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-18 13:17:28',
                'updated_at' => '2025-06-18 13:17:28',
            ),
            15 =>
            array (
                'id' => 16,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 10,
                'uuid' => 'd1480f97-b28f-419c-a157-331c6454dc28',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork Survey',
                'file_name' => 'HOLPA-Fieldwork-Survey.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 26866,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-18 13:17:29',
                'updated_at' => '2025-06-18 13:17:29',
            ),
            16 =>
            array (
                'id' => 17,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 5,
                'uuid' => 'c6210224-4a86-4e98-b41d-c31ab1de639a',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Survey',
                'file_name' => 'HOLPA-Household-Survey.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 121226,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-18 13:17:51',
                'updated_at' => '2025-06-18 13:17:51',
            ),
            17 =>
            array (
                'id' => 18,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 7,
                'uuid' => 'ca33e977-19dc-4163-85a9-1a2413ac1df1',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Survey',
                'file_name' => 'HOLPA-Household-Survey.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 121226,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-18 13:18:07',
                'updated_at' => '2025-06-18 13:18:07',
            ),
            18 =>
            array (
                'id' => 19,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 9,
                'uuid' => 'e7725aa3-7c90-4a9d-a4f2-428ac327cc2e',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Survey',
                'file_name' => 'HOLPA-Household-Survey.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 121226,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-06-18 13:18:19',
                'updated_at' => '2025-06-18 13:18:19',
            ),
        ));


    }
}
