<?php

namespace Database\Seeders\TestRealForms;

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('media')->delete();

        \DB::table('media')->insert(array (
            0 =>
            array (
                'id' => 1,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformTemplate',
                'model_id' => 1,
                'uuid' => '631b4e1c-8592-4e55-8aef-336740eb8f59',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household',
                'file_name' => 'HOLPA-Household.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 268448,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:40:32',
                'updated_at' => '2025-02-20 15:40:32',
            ),
            1 =>
            array (
                'id' => 2,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 1,
                'uuid' => '925e8c1e-b9d7-46ca-9a48-be746786aae9',
                'collection_name' => 'default',
                'name' => 'area_units',
                'file_name' => 'area_units.csv',
                'mime_type' => 'text/csv',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 252,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:42:19',
                'updated_at' => '2025-02-20 15:42:19',
            ),
            2 =>
            array (
                'id' => 3,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 2,
                'uuid' => 'f4a73308-bcda-43da-8f30-8ce23402a4d9',
                'collection_name' => 'default',
                'name' => 'fert_units',
                'file_name' => 'fert_units.csv',
                'mime_type' => 'text/plain',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 126,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:42:19',
                'updated_at' => '2025-02-20 15:42:19',
            ),
            3 =>
            array (
                'id' => 4,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 3,
                'uuid' => 'ab385d97-f3e7-434b-bf9e-bf85b06fb998',
                'collection_name' => 'default',
                'name' => 'yield_units',
                'file_name' => 'yield_units.csv',
                'mime_type' => 'text/csv',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 213,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:42:19',
                'updated_at' => '2025-02-20 15:42:19',
            ),
            4 =>
            array (
                'id' => 5,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformTemplate',
                'model_id' => 2,
                'uuid' => '84fb3fb9-5785-4723-83bd-915693bf958a',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork',
                'file_name' => 'HOLPA-Fieldwork.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 46982,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:51:37',
                'updated_at' => '2025-02-20 15:51:37',
            ),
            5 =>
            array (
                'id' => 6,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 4,
                'uuid' => 'aba5241e-c428-4a4c-8c8b-64082c8c45d3',
                'collection_name' => 'default',
                'name' => 'appearance',
                'file_name' => 'appearance.png',
                'mime_type' => 'image/png',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 1774,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:52:16',
                'updated_at' => '2025-02-20 15:52:16',
            ),
            6 =>
            array (
                'id' => 7,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 5,
                'uuid' => 'f93c31fd-2732-493b-951e-72e3fc4e9af2',
                'collection_name' => 'default',
                'name' => 'disease_incidence',
                'file_name' => 'disease_incidence.png',
                'mime_type' => 'image/jpeg',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 6417,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:52:16',
                'updated_at' => '2025-02-20 15:52:16',
            ),
            7 =>
            array (
                'id' => 8,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 6,
                'uuid' => 'b26c2598-80ca-4b64-91ed-b1e2ff2c9081',
                'collection_name' => 'default',
                'name' => 'insect_incidence',
                'file_name' => 'insect_incidence.png',
                'mime_type' => 'image/jpeg',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 10691,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:52:17',
                'updated_at' => '2025-02-20 15:52:17',
            ),
            8 =>
            array (
                'id' => 9,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 7,
                'uuid' => '00dd086c-32c0-43fd-b9d4-f84582dd8690',
                'collection_name' => 'default',
                'name' => 'soil_sample',
                'file_name' => 'soil_sample.png',
                'mime_type' => 'image/jpeg',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 3105,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:52:17',
                'updated_at' => '2025-02-20 15:52:17',
            ),
            9 =>
            array (
                'id' => 17,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 1,
                'uuid' => 'e193a80a-b675-40e8-a6c4-026ecd6739fa',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Form - Local Shared Test Version',
                'file_name' => 'HOLPA-Household-Form---Local-Shared-Test-Version.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 124453,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 3,
                'created_at' => '2025-02-20 15:57:16',
                'updated_at' => '2025-02-20 15:57:16',
            ),
            10 =>
            array (
                'id' => 19,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 1,
                'uuid' => 'a704ce44-ffe2-4de9-aef7-533c887a419a',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household',
                'file_name' => 'HOLPA-Household.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 213869,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:57:29',
                'updated_at' => '2025-02-20 15:57:29',
            ),
            11 =>
            array (
                'id' => 21,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 1,
                'uuid' => 'a73f1f66-7d15-42f6-a37a-34eee2b405ea',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household',
                'file_name' => 'HOLPA-Household.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 213869,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:57:30',
                'updated_at' => '2025-02-20 15:57:30',
            ),
            12 =>
            array (
                'id' => 22,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 4,
                'uuid' => '7f7914f7-d872-4885-a63b-8e0338f02c12',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork Form - Local Shared Test Version',
                'file_name' => 'HOLPA-Fieldwork-Form---Local-Shared-Test-Version.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 27416,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-02-20 15:57:38',
                'updated_at' => '2025-02-20 15:57:38',
            ),
            13 =>
            array (
                'id' => 24,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 2,
                'uuid' => '2c317372-6995-4caf-a189-36abafbf7e8a',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork',
                'file_name' => 'HOLPA-Fieldwork.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 42358,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:57:42',
                'updated_at' => '2025-02-20 15:57:42',
            ),
            14 =>
            array (
                'id' => 26,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 4,
                'uuid' => '7d77abfb-85a2-4eb8-a5c4-2926ed500268',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork',
                'file_name' => 'HOLPA-Fieldwork.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 42358,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:57:42',
                'updated_at' => '2025-02-20 15:57:42',
            ),
            15 =>
            array (
                'id' => 27,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 2,
                'uuid' => '2f9c1417-405c-495e-afd6-6309eecc8ae4',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Form - Local Shared Test Version',
                'file_name' => 'HOLPA-Household-Form---Local-Shared-Test-Version.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 124453,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-02-20 15:58:19',
                'updated_at' => '2025-02-20 15:58:19',
            ),
            16 =>
            array (
                'id' => 29,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 3,
                'uuid' => 'f7655815-5a07-4a18-ad49-fac077620d66',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household',
                'file_name' => 'HOLPA-Household.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 213869,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:58:31',
                'updated_at' => '2025-02-20 15:58:31',
            ),
            17 =>
            array (
                'id' => 31,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 2,
                'uuid' => 'b8a6275a-ec23-45af-b988-63897ce69f94',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household',
                'file_name' => 'HOLPA-Household.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 213869,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:58:32',
                'updated_at' => '2025-02-20 15:58:32',
            ),
            18 =>
            array (
                'id' => 32,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 5,
                'uuid' => '4211cf24-eaa2-4d45-805b-428691f3c578',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork Form - Local Shared Test Version',
                'file_name' => 'HOLPA-Fieldwork-Form---Local-Shared-Test-Version.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 27416,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-02-20 15:58:39',
                'updated_at' => '2025-02-20 15:58:39',
            ),
            19 =>
            array (
                'id' => 34,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 4,
                'uuid' => '364de171-891e-43b2-8152-88185665a18f',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork',
                'file_name' => 'HOLPA-Fieldwork.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 42358,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:58:43',
                'updated_at' => '2025-02-20 15:58:43',
            ),
            20 =>
            array (
                'id' => 36,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 5,
                'uuid' => 'b6c624c2-b3ad-42b9-9c0b-0c5da99715ba',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork',
                'file_name' => 'HOLPA-Fieldwork.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 42358,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:58:43',
                'updated_at' => '2025-02-20 15:58:43',
            ),
            21 =>
            array (
                'id' => 37,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 3,
                'uuid' => '72e972df-3e59-4412-b95a-857375c125b2',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Form - Local Shared Test Version',
                'file_name' => 'HOLPA-Household-Form---Local-Shared-Test-Version.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 124453,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-02-20 15:59:04',
                'updated_at' => '2025-02-20 15:59:04',
            ),
            22 =>
            array (
                'id' => 39,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 5,
                'uuid' => '6b8a3285-b79e-4f2c-acc7-c0cb75dceed7',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household',
                'file_name' => 'HOLPA-Household.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 213869,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:59:16',
                'updated_at' => '2025-02-20 15:59:16',
            ),
            23 =>
            array (
                'id' => 41,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 3,
                'uuid' => '25036948-cb07-4ed7-be9d-be48ec4bdbaf',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household',
                'file_name' => 'HOLPA-Household.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 213869,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:59:17',
                'updated_at' => '2025-02-20 15:59:17',
            ),
            24 =>
            array (
                'id' => 42,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 6,
                'uuid' => '1691d745-8b00-455c-ae02-ff61e6cda31f',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork Form - Local Shared Test Version',
                'file_name' => 'HOLPA-Fieldwork-Form---Local-Shared-Test-Version.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 27415,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-02-20 16:00:47',
                'updated_at' => '2025-02-20 16:00:47',
            ),
            25 =>
            array (
                'id' => 44,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 6,
                'uuid' => '7ef11d7a-8c9a-4728-ae02-feec2f95402d',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork',
                'file_name' => 'HOLPA-Fieldwork.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 42358,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 16:00:52',
                'updated_at' => '2025-02-20 16:00:52',
            ),
            26 =>
            array (
                'id' => 46,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 6,
                'uuid' => '7bd52f38-0775-4274-96d8-c994ab88c9e0',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork',
                'file_name' => 'HOLPA-Fieldwork.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 42358,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 16:00:52',
                'updated_at' => '2025-02-20 16:00:52',
            ),
        ));


    }
}
