<?php

namespace Database\Seeders\TestRealForms;

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('media')->delete();

        \DB::table('media')->insert(array (
            0 =>
            array (
                'id' => 2,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 1,
                'uuid' => '925e8c1e-b9d7-46ca-9a48-be746786aae9',
                'collection_name' => 'default',
                'name' => 'area_units',
                'file_name' => 'area_units.csv',
                'mime_type' => 'text/csv',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 252,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:42:19',
                'updated_at' => '2025-02-20 15:42:19',
            ),
            1 =>
            array (
                'id' => 3,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 2,
                'uuid' => 'f4a73308-bcda-43da-8f30-8ce23402a4d9',
                'collection_name' => 'default',
                'name' => 'fert_units',
                'file_name' => 'fert_units.csv',
                'mime_type' => 'text/plain',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 126,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:42:19',
                'updated_at' => '2025-02-20 15:42:19',
            ),
            2 =>
            array (
                'id' => 4,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 3,
                'uuid' => 'ab385d97-f3e7-434b-bf9e-bf85b06fb998',
                'collection_name' => 'default',
                'name' => 'yield_units',
                'file_name' => 'yield_units.csv',
                'mime_type' => 'text/csv',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 213,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:42:19',
                'updated_at' => '2025-02-20 15:42:19',
            ),
            3 =>
            array (
                'id' => 6,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 4,
                'uuid' => 'aba5241e-c428-4a4c-8c8b-64082c8c45d3',
                'collection_name' => 'default',
                'name' => 'appearance',
                'file_name' => 'appearance.png',
                'mime_type' => 'image/png',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 1774,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:52:16',
                'updated_at' => '2025-02-20 15:52:16',
            ),
            4 =>
            array (
                'id' => 7,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 5,
                'uuid' => 'f93c31fd-2732-493b-951e-72e3fc4e9af2',
                'collection_name' => 'default',
                'name' => 'disease_incidence',
                'file_name' => 'disease_incidence.png',
                'mime_type' => 'image/jpeg',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 6417,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:52:16',
                'updated_at' => '2025-02-20 15:52:16',
            ),
            5 =>
            array (
                'id' => 8,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 6,
                'uuid' => 'b26c2598-80ca-4b64-91ed-b1e2ff2c9081',
                'collection_name' => 'default',
                'name' => 'insect_incidence',
                'file_name' => 'insect_incidence.png',
                'mime_type' => 'image/jpeg',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 10691,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:52:17',
                'updated_at' => '2025-02-20 15:52:17',
            ),
            6 =>
            array (
                'id' => 9,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 7,
                'uuid' => '00dd086c-32c0-43fd-b9d4-f84582dd8690',
                'collection_name' => 'default',
                'name' => 'soil_sample',
                'file_name' => 'soil_sample.png',
                'mime_type' => 'image/jpeg',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 3105,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:52:17',
                'updated_at' => '2025-02-20 15:52:17',
            ),
            7 =>
            array (
                'id' => 19,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 1,
                'uuid' => 'a704ce44-ffe2-4de9-aef7-533c887a419a',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household',
                'file_name' => 'HOLPA-Household.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 213869,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:57:29',
                'updated_at' => '2025-02-20 15:57:29',
            ),
            8 =>
            array (
                'id' => 24,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 2,
                'uuid' => '2c317372-6995-4caf-a189-36abafbf7e8a',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork',
                'file_name' => 'HOLPA-Fieldwork.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 42358,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:57:42',
                'updated_at' => '2025-02-20 15:57:42',
            ),
            9 =>
            array (
                'id' => 29,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 3,
                'uuid' => 'f7655815-5a07-4a18-ad49-fac077620d66',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household',
                'file_name' => 'HOLPA-Household.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 213869,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:58:31',
                'updated_at' => '2025-02-20 15:58:31',
            ),
            10 =>
            array (
                'id' => 34,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 4,
                'uuid' => '364de171-891e-43b2-8152-88185665a18f',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork',
                'file_name' => 'HOLPA-Fieldwork.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 42358,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:58:43',
                'updated_at' => '2025-02-20 15:58:43',
            ),
            11 =>
            array (
                'id' => 37,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 3,
                'uuid' => '72e972df-3e59-4412-b95a-857375c125b2',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Form - Local Shared Test Version',
                'file_name' => 'HOLPA-Household-Form---Local-Shared-Test-Version.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 124453,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-02-20 15:59:04',
                'updated_at' => '2025-02-20 15:59:04',
            ),
            12 =>
            array (
                'id' => 39,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 5,
                'uuid' => '6b8a3285-b79e-4f2c-acc7-c0cb75dceed7',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household',
                'file_name' => 'HOLPA-Household.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 213869,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:59:16',
                'updated_at' => '2025-02-20 15:59:16',
            ),
            13 =>
            array (
                'id' => 41,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 3,
                'uuid' => '25036948-cb07-4ed7-be9d-be48ec4bdbaf',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household',
                'file_name' => 'HOLPA-Household.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 213869,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 15:59:17',
                'updated_at' => '2025-02-20 15:59:17',
            ),
            14 =>
            array (
                'id' => 42,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 6,
                'uuid' => '1691d745-8b00-455c-ae02-ff61e6cda31f',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork Form - Local Shared Test Version',
                'file_name' => 'HOLPA-Fieldwork-Form---Local-Shared-Test-Version.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 27415,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-02-20 16:00:47',
                'updated_at' => '2025-02-20 16:00:47',
            ),
            15 =>
            array (
                'id' => 44,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 6,
                'uuid' => '7ef11d7a-8c9a-4728-ae02-feec2f95402d',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork',
                'file_name' => 'HOLPA-Fieldwork.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 42358,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 16:00:52',
                'updated_at' => '2025-02-20 16:00:52',
            ),
            16 =>
            array (
                'id' => 46,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 6,
                'uuid' => '7bd52f38-0775-4274-96d8-c994ab88c9e0',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork',
                'file_name' => 'HOLPA-Fieldwork.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 42358,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-20 16:00:52',
                'updated_at' => '2025-02-20 16:00:52',
            ),
            17 =>
            array (
                'id' => 47,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformTemplate',
                'model_id' => 2,
                'uuid' => 'c13adada-95f0-45fa-94c8-81d59edbbe18',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork 2025-03-05',
                'file_name' => 'HOLPA-Fieldwork-2025-03-05.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 106276,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-03-05 10:36:31',
                'updated_at' => '2025-03-05 10:36:31',
            ),
            18 =>
            array (
                'id' => 48,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformTemplate',
                'model_id' => 1,
                'uuid' => '9bed4706-446b-4ac1-a64f-9db65e9be585',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household 2025-03-05',
                'file_name' => 'HOLPA-Household-2025-03-05.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 441743,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-03-05 10:37:59',
                'updated_at' => '2025-03-05 10:37:59',
            ),
            19 =>
            array (
                'id' => 50,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 7,
                'uuid' => '76864889-4ab5-40e3-89c3-62d395421a94',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Form - Local Shared Test Version',
                'file_name' => 'HOLPA-Household-Form---Local-Shared-Test-Version.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 124882,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 4,
                'created_at' => '2025-03-05 14:20:40',
                'updated_at' => '2025-03-05 14:20:40',
            ),
            20 =>
            array (
                'id' => 53,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 8,
                'uuid' => '8ddaaf87-a07f-4ada-89f1-fc3ca988b768',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household 2025-03-05',
                'file_name' => 'HOLPA-Household-2025-03-05.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 453062,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-03-05 14:32:57',
                'updated_at' => '2025-03-05 14:32:57',
            ),
            21 =>
            array (
                'id' => 57,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 1,
                'uuid' => '224c5fde-30d9-4351-90ce-292267d39675',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Form - Local Shared Test Version',
                'file_name' => 'HOLPA-Household-Form---Local-Shared-Test-Version.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 124890,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 6,
                'created_at' => '2025-03-05 14:34:35',
                'updated_at' => '2025-03-05 14:34:35',
            ),
            22 =>
            array (
                'id' => 58,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 9,
                'uuid' => '2fa8871b-825c-40d9-b6bb-8dfb910cf9ed',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Form - Local Shared Test Version',
                'file_name' => 'HOLPA-Household-Form---Local-Shared-Test-Version.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 124882,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 6,
                'created_at' => '2025-03-05 14:34:46',
                'updated_at' => '2025-03-05 14:34:46',
            ),
            23 =>
            array (
                'id' => 60,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 1,
                'uuid' => 'ae5490d5-a9ed-40cb-8a92-8eb20d86427c',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household 2025-03-05',
                'file_name' => 'HOLPA-Household-2025-03-05.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 453062,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-03-05 14:34:48',
                'updated_at' => '2025-03-05 14:34:48',
            ),
            24 =>
            array (
                'id' => 61,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 4,
                'uuid' => '9b0f34dc-cae5-487e-9888-0fa5a812f43e',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork Form - Local Shared Test Version',
                'file_name' => 'HOLPA-Fieldwork-Form---Local-Shared-Test-Version.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 27432,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 3,
                'created_at' => '2025-03-05 14:35:20',
                'updated_at' => '2025-03-05 14:35:20',
            ),
            25 =>
            array (
                'id' => 62,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 10,
                'uuid' => 'cafd13bc-c246-464f-933e-8ec5cb3ef301',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork Form - Local Shared Test Version',
                'file_name' => 'HOLPA-Fieldwork-Form---Local-Shared-Test-Version.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 27425,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 3,
                'created_at' => '2025-03-05 14:35:23',
                'updated_at' => '2025-03-05 14:35:23',
            ),
            26 =>
            array (
                'id' => 64,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 4,
                'uuid' => '8505a52b-826d-419f-a408-dd45fa00928e',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork 2025-03-05',
                'file_name' => 'HOLPA-Fieldwork-2025-03-05.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 109830,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-03-05 14:35:23',
                'updated_at' => '2025-03-05 14:35:23',
            ),
            27 =>
            array (
                'id' => 65,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 2,
                'uuid' => '1741ffab-73ed-482d-83f7-4b697fc32df9',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Form - Local Shared Test Version',
                'file_name' => 'HOLPA-Household-Form---Local-Shared-Test-Version.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 124890,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 3,
                'created_at' => '2025-03-05 14:36:53',
                'updated_at' => '2025-03-05 14:36:53',
            ),
            28 =>
            array (
                'id' => 66,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 11,
                'uuid' => '82332cc3-61f7-42ef-b4b1-59eecf6a73f3',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Form - Local Shared Test Version',
                'file_name' => 'HOLPA-Household-Form---Local-Shared-Test-Version.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 124882,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 3,
                'created_at' => '2025-03-05 14:37:05',
                'updated_at' => '2025-03-05 14:37:05',
            ),
            29 =>
            array (
                'id' => 68,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 2,
                'uuid' => 'ebce05af-f611-4b94-86aa-17a8b3aa81cb',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household 2025-03-05',
                'file_name' => 'HOLPA-Household-2025-03-05.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 453062,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-03-05 14:37:07',
                'updated_at' => '2025-03-05 14:37:07',
            ),
            30 =>
            array (
                'id' => 69,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 5,
                'uuid' => '5b61387d-52d5-4720-9b4b-2992e85cbecf',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork Form - Local Shared Test Version',
                'file_name' => 'HOLPA-Fieldwork-Form---Local-Shared-Test-Version.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 27433,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 3,
                'created_at' => '2025-03-05 14:37:39',
                'updated_at' => '2025-03-05 14:37:39',
            ),
            31 =>
            array (
                'id' => 70,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 12,
                'uuid' => '1ca4cb93-4539-4d24-8c14-21f29abcd8e5',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork Form - Local Shared Test Version',
                'file_name' => 'HOLPA-Fieldwork-Form---Local-Shared-Test-Version.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 27426,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 3,
                'created_at' => '2025-03-05 14:37:42',
                'updated_at' => '2025-03-05 14:37:42',
            ),
            32 =>
            array (
                'id' => 72,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 5,
                'uuid' => 'b5cf2805-54b0-417d-a6b4-7c4524a16939',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Fieldwork 2025-03-05',
                'file_name' => 'HOLPA-Fieldwork-2025-03-05.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 109830,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-03-05 14:37:43',
                'updated_at' => '2025-03-05 14:37:43',
            ),
        ));


    }
}
