<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LanguageStringsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('language_strings')->delete();
        
        \DB::table('language_strings')->insert(array (
            0 => 
            array (
                'id' => 1,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 1,
                'text' => 'Do you drink coffee?',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:28',
                'updated_at' => '2025-01-07 16:20:42',
            ),
            1 => 
            array (
                'id' => 2,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 2,
                'text' => 'How many cups of coffee do you drink in a normal day?',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:28',
                'updated_at' => '2025-01-07 16:20:42',
            ),
            2 => 
            array (
                'id' => 3,
                'locale_id' => 41,
                'language_string_type_id' => 5,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 2,
                'text' => 'Please enter a positive number',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:29',
                'updated_at' => '2025-01-07 16:20:42',
            ),
            3 => 
            array (
                'id' => 4,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 1,
                'text' => 'Yes',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:29',
                'updated_at' => '2025-01-07 16:20:42',
            ),
            4 => 
            array (
                'id' => 5,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 2,
                'text' => 'No',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:29',
                'updated_at' => '2025-01-07 16:20:42',
            ),
            5 => 
            array (
                'id' => 6,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 3,
                'text' => 'This is the first example fom for the workshop on 14th November 2017. WITH AN EDIT',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:30',
                'updated_at' => '2025-01-07 16:20:43',
            ),
            6 => 
            array (
                'id' => 7,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 4,
                'text' => 'What is your name?',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:30',
                'updated_at' => '2025-01-07 16:20:43',
            ),
            7 => 
            array (
                'id' => 8,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 5,
                'text' => 'How old are you?',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:30',
                'updated_at' => '2025-01-07 16:20:43',
            ),
            8 => 
            array (
                'id' => 9,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 3,
                'text' => 'Swipe right to get to the first question',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:30',
                'updated_at' => '2025-01-07 16:20:42',
            ),
            9 => 
            array (
                'id' => 10,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 5,
                'text' => 'This question is optional',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:30',
                'updated_at' => '2025-01-07 16:20:42',
            ),
            10 => 
            array (
                'id' => 11,
                'locale_id' => 41,
                'language_string_type_id' => 5,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 5,
                'text' => 'You entered an invalid number. The respondent must be over 15 yrs old, and is almost certainly less than 150.',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:30',
                'updated_at' => '2025-01-07 16:20:43',
            ),
            11 => 
            array (
                'id' => 12,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 6,
                'text' => 'Which of the following beverages do you drink at least once per month? ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:31',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            12 => 
            array (
                'id' => 13,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 7,
                'text' => 'Drinks Information',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:31',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            13 => 
            array (
                'id' => 14,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 11,
                'text' => 'Overall, how do you find the taste of ${drink_name}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:31',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            14 => 
            array (
                'id' => 15,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 12,
                'text' => 'You said the tast of ${drink_name} was bad. Could you briefly say why you still drink it?',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:31',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            15 => 
            array (
                'id' => 16,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 13,
                'text' => 'Drink Comments',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:31',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            16 => 
            array (
                'id' => 17,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 14,
                'text' => 'Add a comment about this drink. ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:31',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            17 => 
            array (
                'id' => 18,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 6,
                'text' => 'Select all that apply',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:31',
                'updated_at' => '2025-01-07 16:20:43',
            ),
            18 => 
            array (
                'id' => 19,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 12,
                'text' => 'i.e. Do you like other aspects of the drink, or do you find it useful in some way?',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:31',
                'updated_at' => '2025-01-07 16:20:43',
            ),
            19 => 
            array (
                'id' => 20,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 14,
                'text' => 'This is just so we can test nested repeat groups and doesn\'t really make sense as a question. Please add multiple comments if you can.',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:31',
                'updated_at' => '2025-01-07 16:20:43',
            ),
            20 => 
            array (
                'id' => 21,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 3,
                'text' => 'Black tea',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:32',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            21 => 
            array (
                'id' => 22,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 4,
                'text' => 'Green tea',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:32',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            22 => 
            array (
                'id' => 23,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 5,
                'text' => 'Coca-cola',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:32',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            23 => 
            array (
                'id' => 24,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 6,
                'text' => 'Diet coke',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:32',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            24 => 
            array (
                'id' => 25,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 7,
            'text' => 'Fruit juice (any kind)',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:32',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            25 => 
            array (
                'id' => 26,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 8,
                'text' => 'Very good',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:32',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            26 => 
            array (
                'id' => 27,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 9,
                'text' => 'Good',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:32',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            27 => 
            array (
                'id' => 28,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 10,
                'text' => 'Neutral',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:32',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            28 => 
            array (
                'id' => 29,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 11,
                'text' => 'Bad',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:32',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            29 => 
            array (
                'id' => 30,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 12,
                'text' => 'Very bad',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:32',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            30 => 
            array (
                'id' => 31,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 18,
                'text' => 'Can I take a photo?',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:33',
                'updated_at' => '2025-01-07 16:20:45',
            ),
            31 => 
            array (
                'id' => 32,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 19,
                'text' => 'Take a photo of the respondent',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:33',
                'updated_at' => '2025-01-07 16:20:45',
            ),
            32 => 
            array (
                'id' => 33,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 20,
                'text' => 'Please record your current location',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:33',
                'updated_at' => '2025-01-07 16:20:45',
            ),
            33 => 
            array (
                'id' => 34,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 21,
                'text' => 'Thank you for your time. ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:33',
                'updated_at' => '2025-01-07 16:20:45',
            ),
            34 => 
            array (
                'id' => 35,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 18,
                'text' => 'Ask the respondent for permission.',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:33',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            35 => 
            array (
                'id' => 36,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 19,
            'text' => '(Or yourself if you are completing it on your own)',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:33',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            36 => 
            array (
                'id' => 37,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 20,
                'text' => 'If you are outdoors, you should aim for an accuracy of 5-8 metres. If indoors, aim for about 20-30 metres. NOTE - this may take a couple of minutes. ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:33',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            37 => 
            array (
                'id' => 38,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 21,
                'text' => 'Swipe right to end the form and see the options for saving and finalising this instance. ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:33',
                'updated_at' => '2025-01-07 16:20:44',
            ),
            38 => 
            array (
                'id' => 39,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 13,
                'text' => 'Yes',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:34',
                'updated_at' => '2025-01-07 16:20:45',
            ),
            39 => 
            array (
                'id' => 40,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 14,
                'text' => 'No',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:34',
                'updated_at' => '2025-01-07 16:20:45',
            ),
            40 => 
            array (
                'id' => 41,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 23,
                'text' => 'These fields…',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:34',
                'updated_at' => '2025-01-07 16:20:46',
            ),
            41 => 
            array (
                'id' => 42,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 24,
                'text' => '...are not shown…',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:34',
                'updated_at' => '2025-01-07 16:20:46',
            ),
            42 => 
            array (
                'id' => 43,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 25,
                'text' => 'unique identifier for the device used for data collection',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:34',
                'updated_at' => '2025-01-07 16:20:46',
            ),
            43 => 
            array (
                'id' => 44,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 23,
                'text' => 'they are collected...',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:34',
                'updated_at' => '2025-01-07 16:20:45',
            ),
            44 => 
            array (
                'id' => 45,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 24,
                'text' => '...automatically...',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:34',
                'updated_at' => '2025-01-07 16:20:45',
            ),
            45 => 
            array (
                'id' => 46,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 26,
                'text' => 'This is the first example fom for the workshop on 14th November 2017. WITH AN EDIT',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:23',
                'updated_at' => '2025-01-07 16:21:46',
            ),
            46 => 
            array (
                'id' => 47,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 27,
                'text' => 'What is your name?',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:23',
                'updated_at' => '2025-01-07 16:21:46',
            ),
            47 => 
            array (
                'id' => 48,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 28,
                'text' => 'How old are you?',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:23',
                'updated_at' => '2025-01-07 16:21:46',
            ),
            48 => 
            array (
                'id' => 49,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 26,
                'text' => 'Swipe right to get to the first question',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:24',
                'updated_at' => '2025-01-07 16:21:45',
            ),
            49 => 
            array (
                'id' => 50,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 28,
                'text' => 'This question is optional',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:24',
                'updated_at' => '2025-01-07 16:21:45',
            ),
            50 => 
            array (
                'id' => 51,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 26,
                'text' => 'Este es el primer formulario de ejemplo para el taller del 14 de noviembre de 2017. CON UNA EDICIÓN ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:24',
                'updated_at' => '2025-01-07 16:21:47',
            ),
            51 => 
            array (
                'id' => 52,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 27,
                'text' => '¿Cómo te llamas? ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:24',
                'updated_at' => '2025-01-07 16:21:47',
            ),
            52 => 
            array (
                'id' => 53,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 28,
                'text' => '¿Qué edad tienes? ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:24',
                'updated_at' => '2025-01-07 16:21:47',
            ),
            53 => 
            array (
                'id' => 54,
                'locale_id' => 144,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 26,
                'text' => 'Deslice el dedo hacia la derecha para llegar a la primera pregunta ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:25',
                'updated_at' => '2025-01-07 16:21:46',
            ),
            54 => 
            array (
                'id' => 55,
                'locale_id' => 41,
                'language_string_type_id' => 5,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 28,
                'text' => 'You entered an invalid number. The respondent must be over 15 yrs old, and is almost certainly less than 150.',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:25',
                'updated_at' => '2025-01-07 16:21:46',
            ),
            55 => 
            array (
                'id' => 56,
                'locale_id' => 144,
                'language_string_type_id' => 5,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 28,
                'text' => 'Ingresó un número no válido. El encuestado debe tener más de 15 años y es casi seguro que tiene menos de 150.',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:26',
                'updated_at' => '2025-01-07 16:21:46',
            ),
            56 => 
            array (
                'id' => 57,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 29,
                'text' => 'Can I take a photo?',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:27',
                'updated_at' => '2025-01-07 16:21:48',
            ),
            57 => 
            array (
                'id' => 58,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 30,
                'text' => 'Take a photo of the respondent',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:27',
                'updated_at' => '2025-01-07 16:21:48',
            ),
            58 => 
            array (
                'id' => 59,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 31,
                'text' => 'Please record your current location',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:27',
                'updated_at' => '2025-01-07 16:21:48',
            ),
            59 => 
            array (
                'id' => 60,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 32,
                'text' => 'Thank you for your time. ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:27',
                'updated_at' => '2025-01-07 16:21:48',
            ),
            60 => 
            array (
                'id' => 61,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 29,
                'text' => 'Ask the respondent for permission.',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:27',
                'updated_at' => '2025-01-07 16:21:47',
            ),
            61 => 
            array (
                'id' => 62,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 30,
            'text' => '(Or yourself if you are completing it on your own)',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:27',
                'updated_at' => '2025-01-07 16:21:47',
            ),
            62 => 
            array (
                'id' => 63,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 31,
                'text' => 'If you are outdoors, you should aim for an accuracy of 5-8 metres. If indoors, aim for about 20-30 metres. NOTE - this may take a couple of minutes. ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:27',
                'updated_at' => '2025-01-07 16:21:47',
            ),
            63 => 
            array (
                'id' => 64,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 32,
                'text' => 'Swipe right to end the form and see the options for saving and finalising this instance. ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:27',
                'updated_at' => '2025-01-07 16:21:47',
            ),
            64 => 
            array (
                'id' => 65,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 29,
                'text' => '¿Puedo tomar una foto? ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:28',
                'updated_at' => '2025-01-07 16:21:49',
            ),
            65 => 
            array (
                'id' => 66,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 30,
                'text' => 'Toma una foto del encuestado ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:28',
                'updated_at' => '2025-01-07 16:21:49',
            ),
            66 => 
            array (
                'id' => 67,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 31,
                'text' => 'Registre su ubicación actual ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:28',
                'updated_at' => '2025-01-07 16:21:49',
            ),
            67 => 
            array (
                'id' => 68,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 32,
                'text' => 'Gracias por su tiempo.',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:28',
                'updated_at' => '2025-01-07 16:21:49',
            ),
            68 => 
            array (
                'id' => 69,
                'locale_id' => 144,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 29,
                'text' => 'Pida permiso al encuestado. ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:28',
                'updated_at' => '2025-01-07 16:21:48',
            ),
            69 => 
            array (
                'id' => 70,
                'locale_id' => 144,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 30,
            'text' => '(O a usted mismo si lo está completando por su cuenta) ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:28',
                'updated_at' => '2025-01-07 16:21:48',
            ),
            70 => 
            array (
                'id' => 71,
                'locale_id' => 144,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 31,
                'text' => 'Si está al aire libre, debe apuntar a una precisión de 5 a 8 metros. Si está en el interior, apunte a unos 20 a 30 metros. NOTA: esto puede llevar un par de minutos. ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:28',
                'updated_at' => '2025-01-07 16:21:48',
            ),
            71 => 
            array (
                'id' => 72,
                'locale_id' => 144,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 32,
                'text' => 'Deslice el dedo hacia la derecha para finalizar el formulario y ver las opciones para guardar y finalizar esta instancia.',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:28',
                'updated_at' => '2025-01-07 16:21:48',
            ),
            72 => 
            array (
                'id' => 73,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 15,
                'text' => 'Yes',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:29',
                'updated_at' => '2025-01-07 16:21:48',
            ),
            73 => 
            array (
                'id' => 74,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 16,
                'text' => 'No',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:29',
                'updated_at' => '2025-01-07 16:21:48',
            ),
            74 => 
            array (
                'id' => 75,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 15,
                'text' => 'Sí ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:29',
                'updated_at' => '2025-01-07 16:21:49',
            ),
            75 => 
            array (
                'id' => 76,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 16,
                'text' => 'No ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:29',
                'updated_at' => '2025-01-07 16:21:49',
            ),
            76 => 
            array (
                'id' => 77,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 34,
                'text' => 'How many fields are you surveying?',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:30',
                'updated_at' => '2025-01-07 16:21:50',
            ),
            77 => 
            array (
                'id' => 78,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 36,
                'text' => 'What is the main soil type of the field?',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:30',
                'updated_at' => '2025-01-07 16:21:50',
            ),
            78 => 
            array (
                'id' => 79,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 37,
                'text' => 'What is the main crop grown on the field? ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:30',
                'updated_at' => '2025-01-07 16:21:50',
            ),
            79 => 
            array (
                'id' => 80,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 38,
                'text' => 'Add any interesting features of the field.',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:30',
                'updated_at' => '2025-01-07 16:21:50',
            ),
            80 => 
            array (
                'id' => 81,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 34,
                'text' => 'The next section will repeat once per field. If you later need to add more fields, come back and edit this response. ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:30',
                'updated_at' => '2025-01-07 16:21:49',
            ),
            81 => 
            array (
                'id' => 82,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 34,
                'text' => '¿Cuántos campos estás encuestando? ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:31',
                'updated_at' => '2025-01-07 16:21:51',
            ),
            82 => 
            array (
                'id' => 83,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 36,
                'text' => '¿Cuál es el principal tipo de suelo del campo? ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:31',
                'updated_at' => '2025-01-07 16:21:51',
            ),
            83 => 
            array (
                'id' => 84,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 37,
                'text' => '¿Cuál es el cultivo principal que se cultiva en el campo? ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:31',
                'updated_at' => '2025-01-07 16:21:51',
            ),
            84 => 
            array (
                'id' => 85,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 38,
                'text' => 'Agregue alguna característica interesante del campo.',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:31',
                'updated_at' => '2025-01-07 16:21:51',
            ),
            85 => 
            array (
                'id' => 86,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 17,
                'text' => 'clay',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:32',
                'updated_at' => '2025-01-07 16:21:50',
            ),
            86 => 
            array (
                'id' => 87,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 18,
                'text' => 'loam',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:32',
                'updated_at' => '2025-01-07 16:21:50',
            ),
            87 => 
            array (
                'id' => 88,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 19,
                'text' => 'sand',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:32',
                'updated_at' => '2025-01-07 16:21:50',
            ),
            88 => 
            array (
                'id' => 89,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 20,
                'text' => 'silt',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:32',
                'updated_at' => '2025-01-07 16:21:50',
            ),
            89 => 
            array (
                'id' => 90,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 21,
                'text' => 'other',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:32',
                'updated_at' => '2025-01-07 16:21:50',
            ),
            90 => 
            array (
                'id' => 91,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 17,
                'text' => 'arcilla ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:33',
                'updated_at' => '2025-01-07 16:21:51',
            ),
            91 => 
            array (
                'id' => 92,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 18,
                'text' => 'marga ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:33',
                'updated_at' => '2025-01-07 16:21:51',
            ),
            92 => 
            array (
                'id' => 93,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 19,
                'text' => 'arena ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:33',
                'updated_at' => '2025-01-07 16:21:51',
            ),
            93 => 
            array (
                'id' => 94,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 20,
                'text' => 'limo ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:33',
                'updated_at' => '2025-01-07 16:21:51',
            ),
            94 => 
            array (
                'id' => 95,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\ChoiceListEntry',
                'linked_entry_id' => 21,
                'text' => 'otro',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:33',
                'updated_at' => '2025-01-07 16:21:51',
            ),
            95 => 
            array (
                'id' => 96,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 42,
                'text' => 'These fields…',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:33',
                'updated_at' => '2025-01-07 16:21:52',
            ),
            96 => 
            array (
                'id' => 97,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 43,
                'text' => '...are not shown…',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:33',
                'updated_at' => '2025-01-07 16:21:52',
            ),
            97 => 
            array (
                'id' => 98,
                'locale_id' => 41,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 44,
                'text' => 'unique identifier for the device used for data collection',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:33',
                'updated_at' => '2025-01-07 16:21:52',
            ),
            98 => 
            array (
                'id' => 99,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 42,
                'text' => 'they are collected...',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:33',
                'updated_at' => '2025-01-07 16:21:51',
            ),
            99 => 
            array (
                'id' => 100,
                'locale_id' => 41,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 43,
                'text' => '...automatically...',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:33',
                'updated_at' => '2025-01-07 16:21:51',
            ),
            100 => 
            array (
                'id' => 101,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 42,
                'text' => 'Estos campos… ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:34',
                'updated_at' => '2025-01-07 16:21:53',
            ),
            101 => 
            array (
                'id' => 102,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 43,
                'text' => '...no se muestran… ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:34',
                'updated_at' => '2025-01-07 16:21:53',
            ),
            102 => 
            array (
                'id' => 103,
                'locale_id' => 144,
                'language_string_type_id' => 1,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 44,
                'text' => 'Identificador único del dispositivo utilizado para la recopilación de datos ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:34',
                'updated_at' => '2025-01-07 16:21:53',
            ),
            103 => 
            array (
                'id' => 104,
                'locale_id' => 144,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 42,
                'text' => 'se recopilan... ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:34',
                'updated_at' => '2025-01-07 16:21:52',
            ),
            104 => 
            array (
                'id' => 105,
                'locale_id' => 144,
                'language_string_type_id' => 2,
                'linked_entry_type' => 'App\\Models\\Xlsforms\\SurveyRow',
                'linked_entry_id' => 43,
                'text' => '... automáticamente... ',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:21:34',
                'updated_at' => '2025-01-07 16:21:52',
            ),
        ));
        
        
    }
}