<?php

namespace Database\Seeders\TestTemplates;

use Illuminate\Database\Seeder;

class SurveyRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('survey_rows')->delete();

        \DB::table('survey_rows')->insert(array (
            0 =>
            array (
                'id' => 1,
                'xlsform_module_version_id' => 3,
                'row_number' => 9,
                'name' => 'coffee',
                'type' => 'select_one yn',
                'required' => 1,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "coffee", "mediaimage": "coffee.png"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:06',
                'updated_at' => '2025-01-07 16:20:12',
            ),
            1 =>
            array (
                'id' => 2,
                'xlsform_module_version_id' => 3,
                'row_number' => 10,
                'name' => 'coffee_number',
                'type' => 'integer',
                'required' => 1,
                'relevant' => '${coffee}="1"',
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => '.>=0',
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "coffee"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:06',
                'updated_at' => '2025-01-07 16:20:12',
            ),
            2 =>
            array (
                'id' => 3,
                'xlsform_module_version_id' => 2,
                'row_number' => 6,
                'name' => 'na_note1',
                'type' => 'note',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "context"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:06',
                'updated_at' => '2025-01-07 16:20:12',
            ),
            3 =>
            array (
                'id' => 4,
                'xlsform_module_version_id' => 2,
                'row_number' => 7,
                'name' => 'name_of_person',
                'type' => 'text',
                'required' => 1,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "context"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:06',
                'updated_at' => '2025-01-07 16:20:12',
            ),
            4 =>
            array (
                'id' => 5,
                'xlsform_module_version_id' => 2,
                'row_number' => 8,
                'name' => 'age',
                'type' => 'integer',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => '.>15 and .<150',
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "context"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:06',
                'updated_at' => '2025-01-07 16:20:12',
            ),
            5 =>
            array (
                'id' => 6,
                'xlsform_module_version_id' => 4,
                'row_number' => 11,
                'name' => 'drinks',
                'type' => 'select_multiple drinks',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "drinks"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:07',
                'updated_at' => '2025-01-07 16:20:13',
            ),
            6 =>
            array (
                'id' => 7,
                'xlsform_module_version_id' => 4,
                'row_number' => 12,
                'name' => 'drinks_rpt',
                'type' => 'begin repeat',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
            'repeat_count' => 'count-selected(${drinks})',
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "drinks"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:07',
                'updated_at' => '2025-01-07 16:20:13',
            ),
            7 =>
            array (
                'id' => 8,
                'xlsform_module_version_id' => 4,
                'row_number' => 13,
                'name' => 'drink_id',
                'type' => 'calculate',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
            'calculation' => 'selected-at(${drinks},position(..)-1)',
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "drinks"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:07',
                'updated_at' => '2025-01-07 16:20:13',
            ),
            8 =>
            array (
                'id' => 9,
                'xlsform_module_version_id' => 4,
                'row_number' => 14,
                'name' => 'drinks_rpt_grp',
                'type' => 'begin group',
                'required' => 0,
            'relevant' => 'count-selected(${drinks}) >= position(..)',
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "drinks"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:07',
                'updated_at' => '2025-01-07 16:20:13',
            ),
            9 =>
            array (
                'id' => 10,
                'xlsform_module_version_id' => 4,
                'row_number' => 15,
                'name' => 'drink_name',
                'type' => 'calculate',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
            'calculation' => 'jr:choice-name(${drink_id}, \'${drinks}\')',
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "drinks"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:07',
                'updated_at' => '2025-01-07 16:20:13',
            ),
            10 =>
            array (
                'id' => 11,
                'xlsform_module_version_id' => 4,
                'row_number' => 16,
                'name' => 'drink_lk',
                'type' => 'select_one lk',
                'required' => 1,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "drinks"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:07',
                'updated_at' => '2025-01-07 16:20:13',
            ),
            11 =>
            array (
                'id' => 12,
                'xlsform_module_version_id' => 4,
                'row_number' => 17,
                'name' => 'why_drink',
                'type' => 'text',
                'required' => 1,
                'relevant' => '${drink_lk} = \'very_bad\' or ${drink_lk} = \'bad\'',
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "drinks"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:07',
                'updated_at' => '2025-01-07 16:20:13',
            ),
            12 =>
            array (
                'id' => 13,
                'xlsform_module_version_id' => 4,
                'row_number' => 18,
                'name' => 'drink_comment_rpt',
                'type' => 'begin repeat',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "drinks"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:07',
                'updated_at' => '2025-01-07 16:20:13',
            ),
            13 =>
            array (
                'id' => 14,
                'xlsform_module_version_id' => 4,
                'row_number' => 19,
                'name' => 'drink_comment',
                'type' => 'text',
                'required' => 1,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "drinks"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:07',
                'updated_at' => '2025-01-07 16:20:13',
            ),
            14 =>
            array (
                'id' => 15,
                'xlsform_module_version_id' => 4,
                'row_number' => 20,
                'name' => 'drink_comment_rpt',
                'type' => 'end repeat',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "drinks"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:07',
                'updated_at' => '2025-01-07 16:20:13',
            ),
            15 =>
            array (
                'id' => 16,
                'xlsform_module_version_id' => 4,
                'row_number' => 21,
                'name' => 'drinks_rpt_grp',
                'type' => 'end group',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "drinks"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:07',
                'updated_at' => '2025-01-07 16:20:13',
            ),
            16 =>
            array (
                'id' => 17,
                'xlsform_module_version_id' => 4,
                'row_number' => 22,
                'name' => 'driinks_rpt',
                'type' => 'end repeat',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "drinks"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:07',
                'updated_at' => '2025-01-07 16:20:13',
            ),
            17 =>
            array (
                'id' => 18,
                'xlsform_module_version_id' => 5,
                'row_number' => 23,
                'name' => 'photo_yn',
                'type' => 'select_one yn',
                'required' => 1,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "end"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:07',
                'updated_at' => '2025-01-07 16:20:14',
            ),
            18 =>
            array (
                'id' => 19,
                'xlsform_module_version_id' => 5,
                'row_number' => 24,
                'name' => 'photo',
                'type' => 'photo',
                'required' => 1,
                'relevant' => '${photo_yn}="1"',
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "end"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:07',
                'updated_at' => '2025-01-07 16:20:14',
            ),
            19 =>
            array (
                'id' => 20,
                'xlsform_module_version_id' => 5,
                'row_number' => 25,
                'name' => 'gps',
                'type' => 'geopoint',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "end"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:07',
                'updated_at' => '2025-01-07 16:20:14',
            ),
            20 =>
            array (
                'id' => 21,
                'xlsform_module_version_id' => 5,
                'row_number' => 26,
                'name' => 'na_note2',
                'type' => 'note',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "end"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:07',
                'updated_at' => '2025-01-07 16:20:14',
            ),
            21 =>
            array (
                'id' => 22,
                'xlsform_module_version_id' => 1,
                'row_number' => 2,
                'name' => 'starttime',
                'type' => 'start',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "metadata"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:08',
                'updated_at' => '2025-01-07 16:20:15',
            ),
            22 =>
            array (
                'id' => 23,
                'xlsform_module_version_id' => 1,
                'row_number' => 3,
                'name' => 'endtime',
                'type' => 'end',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "metadata"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:08',
                'updated_at' => '2025-01-07 16:20:15',
            ),
            23 =>
            array (
                'id' => 24,
                'xlsform_module_version_id' => 1,
                'row_number' => 4,
                'name' => 'todaydate',
                'type' => 'today',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "metadata"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:08',
                'updated_at' => '2025-01-07 16:20:15',
            ),
            24 =>
            array (
                'id' => 25,
                'xlsform_module_version_id' => 1,
                'row_number' => 5,
                'name' => 'deviceid',
                'type' => 'deviceid',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "metadata"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:08',
                'updated_at' => '2025-01-07 16:20:15',
            ),
            25 =>
            array (
                'id' => 26,
                'xlsform_module_version_id' => 7,
                'row_number' => 6,
                'name' => 'na_note1',
                'type' => 'note',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "context"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:55',
                'updated_at' => '2025-01-07 16:21:01',
            ),
            26 =>
            array (
                'id' => 27,
                'xlsform_module_version_id' => 7,
                'row_number' => 7,
                'name' => 'name_of_person',
                'type' => 'text',
                'required' => 1,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "context"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:55',
                'updated_at' => '2025-01-07 16:21:01',
            ),
            27 =>
            array (
                'id' => 28,
                'xlsform_module_version_id' => 7,
                'row_number' => 8,
                'name' => 'age',
                'type' => 'integer',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => '.>15 and .<150',
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "context"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:55',
                'updated_at' => '2025-01-07 16:21:01',
            ),
            28 =>
            array (
                'id' => 29,
                'xlsform_module_version_id' => 9,
                'row_number' => 17,
                'name' => 'photo_yn',
                'type' => 'select_one yn',
                'required' => 1,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "end"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:56',
                'updated_at' => '2025-01-07 16:21:01',
            ),
            29 =>
            array (
                'id' => 30,
                'xlsform_module_version_id' => 9,
                'row_number' => 18,
                'name' => 'photo',
                'type' => 'photo',
                'required' => 1,
                'relevant' => '${photo_yn}="1"',
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "end"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:56',
                'updated_at' => '2025-01-07 16:21:01',
            ),
            30 =>
            array (
                'id' => 31,
                'xlsform_module_version_id' => 9,
                'row_number' => 19,
                'name' => 'gps',
                'type' => 'geopoint',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "end"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:56',
                'updated_at' => '2025-01-07 16:21:01',
            ),
            31 =>
            array (
                'id' => 32,
                'xlsform_module_version_id' => 9,
                'row_number' => 20,
                'name' => 'na_note2',
                'type' => 'note',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "end"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:56',
                'updated_at' => '2025-01-07 16:21:01',
            ),
            32 =>
            array (
                'id' => 33,
                'xlsform_module_version_id' => 8,
                'row_number' => 9,
                'name' => 'fieldwork',
                'type' => 'begin_group',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:56',
                'updated_at' => '2025-01-07 16:21:02',
            ),
            33 =>
            array (
                'id' => 34,
                'xlsform_module_version_id' => 8,
                'row_number' => 10,
                'name' => 'field_count',
                'type' => 'integer',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:56',
                'updated_at' => '2025-01-07 16:21:02',
            ),
            34 =>
            array (
                'id' => 35,
                'xlsform_module_version_id' => 8,
                'row_number' => 11,
                'name' => 'fieldwork_repeat',
                'type' => 'begin_repeat',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:56',
                'updated_at' => '2025-01-07 16:21:02',
            ),
            35 =>
            array (
                'id' => 36,
                'xlsform_module_version_id' => 8,
                'row_number' => 12,
                'name' => 'soil_type',
                'type' => 'select_one soils',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:56',
                'updated_at' => '2025-01-07 16:21:02',
            ),
            36 =>
            array (
                'id' => 37,
                'xlsform_module_version_id' => 8,
                'row_number' => 13,
                'name' => 'crop_types',
                'type' => 'text',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:56',
                'updated_at' => '2025-01-07 16:21:02',
            ),
            37 =>
            array (
                'id' => 38,
                'xlsform_module_version_id' => 8,
                'row_number' => 14,
                'name' => 'interesting_features',
                'type' => 'text',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:56',
                'updated_at' => '2025-01-07 16:21:02',
            ),
            38 =>
            array (
                'id' => 39,
                'xlsform_module_version_id' => 8,
                'row_number' => 15,
                'name' => 'fieldwork_repeat',
                'type' => 'end_repeat',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:56',
                'updated_at' => '2025-01-07 16:21:02',
            ),
            39 =>
            array (
                'id' => 40,
                'xlsform_module_version_id' => 8,
                'row_number' => 16,
                'name' => 'fieldwork',
                'type' => 'end_group',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:56',
                'updated_at' => '2025-01-07 16:21:02',
            ),
            40 =>
            array (
                'id' => 41,
                'xlsform_module_version_id' => 6,
                'row_number' => 2,
                'name' => 'starttime',
                'type' => 'start',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "metadata"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:57',
                'updated_at' => '2025-01-07 16:21:02',
            ),
            41 =>
            array (
                'id' => 42,
                'xlsform_module_version_id' => 6,
                'row_number' => 3,
                'name' => 'endtime',
                'type' => 'end',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "metadata"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:57',
                'updated_at' => '2025-01-07 16:21:02',
            ),
            42 =>
            array (
                'id' => 43,
                'xlsform_module_version_id' => 6,
                'row_number' => 4,
                'name' => 'todaydate',
                'type' => 'today',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "metadata"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:57',
                'updated_at' => '2025-01-07 16:21:02',
            ),
            43 =>
            array (
                'id' => 44,
                'xlsform_module_version_id' => 6,
                'row_number' => 5,
                'name' => 'deviceid',
                'type' => 'deviceid',
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "metadata"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:20:57',
                'updated_at' => '2025-01-07 16:21:02',
            ),
        ));


    }
}
