<?php

namespace Database\Seeders\TestMiniForms;

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('media')->delete();

        \DB::table('media')->insert(array (
            0 =>
            array (
                'id' => 3,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\RequiredMedia',
                'model_id' => 1,
                'uuid' => '7375292f-748e-4547-80dc-0216a1b1cf4b',
                'collection_name' => 'default',
                'name' => 'coffee',
                'file_name' => 'coffee.png',
                'mime_type' => 'image/png',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 3205,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-01-16 14:41:36',
                'updated_at' => '2025-01-16 14:41:36',
            ),
            1 =>
            array (
                'id' => 4,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformTemplate',
                'model_id' => 1,
                'uuid' => '4170e5dc-dcff-4ee3-81df-9b46744caf50',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Mini Example',
                'file_name' => 'HOLPA-Household-Mini-Example.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 19107,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-12 11:13:12',
                'updated_at' => '2025-02-12 11:13:12',
            ),
            2 =>
            array (
                'id' => 5,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformTemplate',
                'model_id' => 2,
                'uuid' => '25fd1c4e-c049-49df-af93-8315f30e6f3c',
                'collection_name' => 'xlsform_file',
                'name' => 'Holpa Fieldwork Mini Example',
                'file_name' => 'Holpa-Fieldwork-Mini-Example.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 19962,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-12 11:19:25',
                'updated_at' => '2025-02-12 11:19:25',
            ),
            3 =>
            array (
                'id' => 8,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 1,
                'uuid' => 'a516799c-dd37-413a-b4f2-c2b474ad325e',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Mini Example',
                'file_name' => 'HOLPA-Household-Mini-Example.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 14767,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-12 11:20:35',
                'updated_at' => '2025-02-12 11:20:35',
            ),
            4 =>
            array (
                'id' => 13,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 2,
                'uuid' => 'e83be5bc-b91f-4c8d-ab60-1aef4a50905d',
                'collection_name' => 'xlsform_file',
                'name' => 'Holpa Fieldwork Mini Example',
                'file_name' => 'Holpa-Fieldwork-Mini-Example.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 15694,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-12 11:20:45',
                'updated_at' => '2025-02-12 11:20:45',
            ),
            5 =>
            array (
                'id' => 18,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 3,
                'uuid' => '79db01cf-a9c0-4c78-9bbe-db3c31f3a3da',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Mini Example',
                'file_name' => 'HOLPA-Household-Mini-Example.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 14768,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-12 11:21:04',
                'updated_at' => '2025-02-12 11:21:04',
            ),
            6 =>
            array (
                'id' => 20,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 9,
                'uuid' => '07f933cb-5869-4768-a277-8462cad9aaf9',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Mini Example',
                'file_name' => 'HOLPA-Household-Mini-Example.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 14763,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-12 11:21:04',
                'updated_at' => '2025-02-12 11:21:04',
            ),
            7 =>
            array (
                'id' => 23,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 4,
                'uuid' => 'd40ecb70-1bd6-4fb4-932f-1323500338d6',
                'collection_name' => 'xlsform_file',
                'name' => 'Holpa Fieldwork Mini Example',
                'file_name' => 'Holpa-Fieldwork-Mini-Example.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 15696,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-12 11:21:10',
                'updated_at' => '2025-02-12 11:21:10',
            ),
            8 =>
            array (
                'id' => 25,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 12,
                'uuid' => 'ef297f89-a7b4-4839-899c-4ac1148c76f2',
                'collection_name' => 'xlsform_file',
                'name' => 'Holpa Fieldwork Mini Example',
                'file_name' => 'Holpa-Fieldwork-Mini-Example.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 15696,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-12 11:21:10',
                'updated_at' => '2025-02-12 11:21:10',
            ),
            9 =>
            array (
                'id' => 28,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 5,
                'uuid' => 'f1135eed-1791-44ec-9a0e-e0580cdfdfc6',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Mini Example',
                'file_name' => 'HOLPA-Household-Mini-Example.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 14767,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-12 11:21:17',
                'updated_at' => '2025-02-12 11:21:17',
            ),
            10 =>
            array (
                'id' => 30,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 10,
                'uuid' => '7a19bec1-354c-48af-81d1-086abcf2bc3a',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Mini Example',
                'file_name' => 'HOLPA-Household-Mini-Example.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 14763,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-12 11:21:17',
                'updated_at' => '2025-02-12 11:21:17',
            ),
            11 =>
            array (
                'id' => 33,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 6,
                'uuid' => '1808b67f-7350-4000-8eea-9942f851db0d',
                'collection_name' => 'xlsform_file',
                'name' => 'Holpa Fieldwork Mini Example',
                'file_name' => 'Holpa-Fieldwork-Mini-Example.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 15696,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-12 11:21:23',
                'updated_at' => '2025-02-12 11:21:23',
            ),
            12 =>
            array (
                'id' => 35,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 13,
                'uuid' => '6a07b2c0-93c0-4f68-8741-804af63d1095',
                'collection_name' => 'xlsform_file',
                'name' => 'Holpa Fieldwork Mini Example',
                'file_name' => 'Holpa-Fieldwork-Mini-Example.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'local',
                'conversions_disk' => 'local',
                'size' => 15696,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-12 11:21:23',
                'updated_at' => '2025-02-12 11:21:23',
            ),
            13 =>
            array (
                'id' => 36,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 8,
                'uuid' => 'b1aedb4b-efe6-4ff1-852f-251fb6862216',
                'collection_name' => 'xlsform_file',
                'name' => 'Test Mini HOLPA Household Survey',
                'file_name' => 'Test-Mini-HOLPA-Household-Survey.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 12301,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-02-12 11:53:10',
                'updated_at' => '2025-02-12 11:53:10',
            ),
            14 =>
            array (
                'id' => 37,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 7,
                'uuid' => '26a8a4cf-aa3e-46cd-8549-0b0c93a19fba',
                'collection_name' => 'xlsform_file',
                'name' => 'Test Mini HOLPA Household Survey',
                'file_name' => 'Test-Mini-HOLPA-Household-Survey.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 12284,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-02-12 11:53:12',
                'updated_at' => '2025-02-12 11:53:12',
            ),
            15 =>
            array (
                'id' => 39,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 8,
                'uuid' => '4c6ef7aa-fc19-4c74-b61b-170aee291a64',
                'collection_name' => 'xlsform_file',
                'name' => 'HOLPA Household Mini Example',
                'file_name' => 'HOLPA-Household-Mini-Example.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 14763,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-12 11:53:12',
                'updated_at' => '2025-02-12 11:53:12',
            ),
            16 =>
            array (
                'id' => 40,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 11,
                'uuid' => '30ce88cb-ad5a-4fdf-a220-bb30b2d1a13c',
                'collection_name' => 'xlsform_file',
                'name' => 'Test Mini HOLPA Fieldwork Survey',
                'file_name' => 'Test-Mini-HOLPA-Fieldwork-Survey.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 11652,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-02-12 12:01:38',
                'updated_at' => '2025-02-12 12:01:38',
            ),
            17 =>
            array (
                'id' => 41,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\XlsformVersion',
                'model_id' => 9,
                'uuid' => 'c36bcb30-ac1d-4024-8c7e-a918984138f3',
                'collection_name' => 'xlsform_file',
                'name' => 'Test Mini HOLPA Fieldwork Survey',
                'file_name' => 'Test-Mini-HOLPA-Fieldwork-Survey.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 11639,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-02-12 12:01:40',
                'updated_at' => '2025-02-12 12:01:40',
            ),
            18 =>
            array (
                'id' => 43,
                'model_type' => 'Stats4sd\\FilamentOdkLink\\Models\\OdkLink\\Xlsform',
                'model_id' => 11,
                'uuid' => 'ebe76f68-dcd4-4bdc-8f06-6f327aad8fd2',
                'collection_name' => 'xlsform_file',
                'name' => 'Holpa Fieldwork Mini Example',
                'file_name' => 'Holpa-Fieldwork-Mini-Example.xlsx',
                'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 15696,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-02-12 12:01:40',
                'updated_at' => '2025-02-12 12:01:40',
            ),
        ));


    }
}
