<?php

namespace Database\Seeders\TestMiniForms;

use Illuminate\Database\Seeder;

class SurveyRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('survey_rows')->delete();

        \DB::table('survey_rows')->insert(array (
            0 =>
            array (
                'id' => 1,
                'xlsform_module_version_id' => 3,
                'row_number' => 10,
                'name' => 'coffee',
                'repeat_group_path' => NULL,
                'path' => '/coffee',
                'type' => 'select_one yn',
                'choice_list_id' => 1,
                'required' => 1,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "coffee", "mediaimage": "coffee.png"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:17',
                'updated_at' => '2025-03-27 13:44:39',
            ),
            1 =>
            array (
                'id' => 2,
                'xlsform_module_version_id' => 3,
                'row_number' => 11,
                'name' => 'coffee_number',
                'repeat_group_path' => NULL,
                'path' => '/coffee_number',
                'type' => 'integer',
                'choice_list_id' => NULL,
                'required' => 1,
                'relevant' => '${coffee}="1"',
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => '.>=0',
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "coffee"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:17',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            2 =>
            array (
                'id' => 3,
                'xlsform_module_version_id' => 2,
                'row_number' => 6,
                'name' => 'time_frame',
                'repeat_group_path' => NULL,
                'path' => '/time_frame',
                'type' => 'calculate',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => '"in the last 12 months"',
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "context"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:18',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            3 =>
            array (
                'id' => 4,
                'xlsform_module_version_id' => 2,
                'row_number' => 7,
                'name' => 'na_note1',
                'repeat_group_path' => NULL,
                'path' => '/na_note1',
                'type' => 'note',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "context"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:18',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            4 =>
            array (
                'id' => 5,
                'xlsform_module_version_id' => 2,
                'row_number' => 8,
                'name' => 'name_of_person',
                'repeat_group_path' => NULL,
                'path' => '/name_of_person',
                'type' => 'text',
                'choice_list_id' => NULL,
                'required' => 1,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "context"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:18',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            5 =>
            array (
                'id' => 6,
                'xlsform_module_version_id' => 2,
                'row_number' => 9,
                'name' => 'age',
                'repeat_group_path' => NULL,
                'path' => '/age',
                'type' => 'integer',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => '.>15 and .<150',
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "context"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:18',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            6 =>
            array (
                'id' => 7,
                'xlsform_module_version_id' => 4,
                'row_number' => 12,
                'name' => 'drinks',
                'repeat_group_path' => NULL,
                'path' => '/drinks',
                'type' => 'select_multiple drinks',
                'choice_list_id' => 2,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "diet_quality"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:18',
                'updated_at' => '2025-03-27 13:44:39',
            ),
            7 =>
            array (
                'id' => 8,
                'xlsform_module_version_id' => 4,
                'row_number' => 13,
                'name' => 'drinks_rpt',
                'repeat_group_path' => NULL,
                'path' => '/drinks_rpt/',
                'type' => 'begin repeat',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
            'repeat_count' => 'count-selected(${drinks})',
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "diet_quality"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:18',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            8 =>
            array (
                'id' => 9,
                'xlsform_module_version_id' => 4,
                'row_number' => 14,
                'name' => 'drink_id',
                'repeat_group_path' => NULL,
                'path' => '/drinks_rpt/drink_id',
                'type' => 'calculate',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
            'calculation' => 'selected-at(${drinks},position(..)-1)',
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "diet_quality"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:18',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            9 =>
            array (
                'id' => 10,
                'xlsform_module_version_id' => 4,
                'row_number' => 15,
                'name' => 'drinks_rpt_grp',
                'repeat_group_path' => NULL,
                'path' => '/drinks_rpt/drinks_rpt_grp/',
                'type' => 'begin group',
                'choice_list_id' => NULL,
                'required' => 0,
            'relevant' => 'count-selected(${drinks}) >= position(..)',
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "diet_quality"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:18',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            10 =>
            array (
                'id' => 11,
                'xlsform_module_version_id' => 4,
                'row_number' => 16,
                'name' => 'drink_name',
                'repeat_group_path' => NULL,
                'path' => '/drinks_rpt/drinks_rpt_grp/drink_name',
                'type' => 'calculate',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
            'calculation' => 'jr:choice-name(${drink_id}, \'${drinks}\')',
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "diet_quality"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:18',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            11 =>
            array (
                'id' => 12,
                'xlsform_module_version_id' => 4,
                'row_number' => 17,
                'name' => 'drink_lk',
                'repeat_group_path' => NULL,
                'path' => '/drinks_rpt/drinks_rpt_grp/drink_lk',
                'type' => 'select_one lk',
                'choice_list_id' => 3,
                'required' => 1,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "diet_quality"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:18',
                'updated_at' => '2025-03-27 13:44:39',
            ),
            12 =>
            array (
                'id' => 13,
                'xlsform_module_version_id' => 4,
                'row_number' => 18,
                'name' => 'why_drink',
                'repeat_group_path' => NULL,
                'path' => '/drinks_rpt/drinks_rpt_grp/why_drink',
                'type' => 'text',
                'choice_list_id' => NULL,
                'required' => 1,
                'relevant' => '${drink_lk} = \'very_bad\' or ${drink_lk} = \'bad\'',
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "diet_quality"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:18',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            13 =>
            array (
                'id' => 14,
                'xlsform_module_version_id' => 4,
                'row_number' => 19,
                'name' => 'drink_comment_rpt',
                'repeat_group_path' => NULL,
                'path' => '/drinks_rpt/drinks_rpt_grp/drink_comment_rpt/',
                'type' => 'begin repeat',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "diet_quality"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:18',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            14 =>
            array (
                'id' => 15,
                'xlsform_module_version_id' => 4,
                'row_number' => 20,
                'name' => 'drink_comment',
                'repeat_group_path' => NULL,
                'path' => '/drinks_rpt/drinks_rpt_grp/drink_comment_rpt/drink_comment',
                'type' => 'text',
                'choice_list_id' => NULL,
                'required' => 1,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "diet_quality"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:18',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            15 =>
            array (
                'id' => 16,
                'xlsform_module_version_id' => 4,
                'row_number' => 21,
                'name' => 'drink_comment_rpt',
                'repeat_group_path' => NULL,
                'path' => '/drinks_rpt/drinks_rpt_grp/',
                'type' => 'end repeat',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "diet_quality"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:18',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            16 =>
            array (
                'id' => 17,
                'xlsform_module_version_id' => 4,
                'row_number' => 22,
                'name' => 'drinks_rpt_grp',
                'repeat_group_path' => NULL,
                'path' => '/drinks_rpt/',
                'type' => 'end group',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "diet_quality"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:18',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            17 =>
            array (
                'id' => 18,
                'xlsform_module_version_id' => 4,
                'row_number' => 23,
                'name' => 'driinks_rpt',
                'repeat_group_path' => NULL,
                'path' => '/',
                'type' => 'end repeat',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "diet_quality"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:18',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            18 =>
            array (
                'id' => 19,
                'xlsform_module_version_id' => 5,
                'row_number' => 24,
                'name' => 'photo_yn',
                'repeat_group_path' => NULL,
                'path' => '/photo_yn',
                'type' => 'select_one yn',
                'choice_list_id' => 4,
                'required' => 1,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "end"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:19',
                'updated_at' => '2025-03-27 13:44:39',
            ),
            19 =>
            array (
                'id' => 20,
                'xlsform_module_version_id' => 5,
                'row_number' => 25,
                'name' => 'photo',
                'repeat_group_path' => NULL,
                'path' => '/photo',
                'type' => 'photo',
                'choice_list_id' => NULL,
                'required' => 1,
                'relevant' => '${photo_yn}="1"',
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "end"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:19',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            20 =>
            array (
                'id' => 21,
                'xlsform_module_version_id' => 5,
                'row_number' => 26,
                'name' => 'gps',
                'repeat_group_path' => NULL,
                'path' => '/gps',
                'type' => 'geopoint',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "end"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:19',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            21 =>
            array (
                'id' => 22,
                'xlsform_module_version_id' => 5,
                'row_number' => 27,
                'name' => 'na_note2',
                'repeat_group_path' => NULL,
                'path' => '/na_note2',
                'type' => 'note',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "end"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:19',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            22 =>
            array (
                'id' => 23,
                'xlsform_module_version_id' => 1,
                'row_number' => 2,
                'name' => 'starttime',
                'repeat_group_path' => NULL,
                'path' => '/starttime',
                'type' => 'start',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "metadata"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:20',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            23 =>
            array (
                'id' => 24,
                'xlsform_module_version_id' => 1,
                'row_number' => 3,
                'name' => 'endtime',
                'repeat_group_path' => NULL,
                'path' => '/endtime',
                'type' => 'end',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "metadata"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:20',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            24 =>
            array (
                'id' => 25,
                'xlsform_module_version_id' => 1,
                'row_number' => 4,
                'name' => 'todaydate',
                'repeat_group_path' => NULL,
                'path' => '/todaydate',
                'type' => 'today',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "metadata"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:20',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            25 =>
            array (
                'id' => 26,
                'xlsform_module_version_id' => 1,
                'row_number' => 5,
                'name' => 'deviceid',
                'repeat_group_path' => NULL,
                'path' => '/deviceid',
                'type' => 'deviceid',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "metadata"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 16:56:20',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            26 =>
            array (
                'id' => 27,
                'xlsform_module_version_id' => 7,
                'row_number' => 6,
                'name' => 'na_note1',
                'repeat_group_path' => NULL,
                'path' => '/na_note1',
                'type' => 'note',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "context_fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:45',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            27 =>
            array (
                'id' => 28,
                'xlsform_module_version_id' => 7,
                'row_number' => 7,
                'name' => 'name_of_person',
                'repeat_group_path' => NULL,
                'path' => '/name_of_person',
                'type' => 'text',
                'choice_list_id' => NULL,
                'required' => 1,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "context_fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:45',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            28 =>
            array (
                'id' => 29,
                'xlsform_module_version_id' => 7,
                'row_number' => 8,
                'name' => 'age',
                'repeat_group_path' => NULL,
                'path' => '/age',
                'type' => 'integer',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => '.>15 and .<150',
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "context_fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:45',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            29 =>
            array (
                'id' => 30,
                'xlsform_module_version_id' => 9,
                'row_number' => 17,
                'name' => 'photo_yn',
                'repeat_group_path' => NULL,
                'path' => '/photo_yn',
                'type' => 'select_one yn',
                'choice_list_id' => 5,
                'required' => 1,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "end_fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:45',
                'updated_at' => '2025-03-27 13:44:39',
            ),
            30 =>
            array (
                'id' => 31,
                'xlsform_module_version_id' => 9,
                'row_number' => 18,
                'name' => 'photo',
                'repeat_group_path' => NULL,
                'path' => '/photo',
                'type' => 'photo',
                'choice_list_id' => NULL,
                'required' => 1,
                'relevant' => '${photo_yn}="1"',
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "end_fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:45',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            31 =>
            array (
                'id' => 32,
                'xlsform_module_version_id' => 9,
                'row_number' => 19,
                'name' => 'gps',
                'repeat_group_path' => NULL,
                'path' => '/gps',
                'type' => 'geopoint',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "end_fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:45',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            32 =>
            array (
                'id' => 33,
                'xlsform_module_version_id' => 9,
                'row_number' => 20,
                'name' => 'na_note2',
                'repeat_group_path' => NULL,
                'path' => '/na_note2',
                'type' => 'note',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "end_fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:45',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            33 =>
            array (
                'id' => 34,
                'xlsform_module_version_id' => 8,
                'row_number' => 9,
                'name' => 'fieldwork',
                'repeat_group_path' => NULL,
                'path' => '/fieldwork/',
                'type' => 'begin_group',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:46',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            34 =>
            array (
                'id' => 35,
                'xlsform_module_version_id' => 8,
                'row_number' => 10,
                'name' => 'field_count',
                'repeat_group_path' => NULL,
                'path' => '/fieldwork/field_count',
                'type' => 'integer',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:46',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            35 =>
            array (
                'id' => 36,
                'xlsform_module_version_id' => 8,
                'row_number' => 11,
                'name' => 'fieldwork_repeat',
                'repeat_group_path' => NULL,
                'path' => '/fieldwork/fieldwork_repeat/',
                'type' => 'begin_repeat',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:46',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            36 =>
            array (
                'id' => 37,
                'xlsform_module_version_id' => 8,
                'row_number' => 12,
                'name' => 'soil_type',
                'repeat_group_path' => NULL,
                'path' => '/fieldwork/fieldwork_repeat/soil_type',
                'type' => 'select_one soils',
                'choice_list_id' => 6,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:46',
                'updated_at' => '2025-03-27 13:44:39',
            ),
            37 =>
            array (
                'id' => 38,
                'xlsform_module_version_id' => 8,
                'row_number' => 13,
                'name' => 'crop_types',
                'repeat_group_path' => NULL,
                'path' => '/fieldwork/fieldwork_repeat/crop_types',
                'type' => 'select_one crops',
                'choice_list_id' => 7,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:46',
                'updated_at' => '2025-03-27 13:44:39',
            ),
            38 =>
            array (
                'id' => 39,
                'xlsform_module_version_id' => 8,
                'row_number' => 14,
                'name' => 'interesting_features',
                'repeat_group_path' => NULL,
                'path' => '/fieldwork/fieldwork_repeat/interesting_features',
                'type' => 'text',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:46',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            39 =>
            array (
                'id' => 40,
                'xlsform_module_version_id' => 8,
                'row_number' => 15,
                'name' => 'fieldwork_repeat',
                'repeat_group_path' => NULL,
                'path' => '/fieldwork/',
                'type' => 'end_repeat',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:46',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            40 =>
            array (
                'id' => 41,
                'xlsform_module_version_id' => 8,
                'row_number' => 16,
                'name' => 'fieldwork',
                'repeat_group_path' => NULL,
                'path' => '/',
                'type' => 'end_group',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:46',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            41 =>
            array (
                'id' => 42,
                'xlsform_module_version_id' => 6,
                'row_number' => 2,
                'name' => 'starttime',
                'repeat_group_path' => NULL,
                'path' => '/starttime',
                'type' => 'start',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "metadata_fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:47',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            42 =>
            array (
                'id' => 43,
                'xlsform_module_version_id' => 6,
                'row_number' => 3,
                'name' => 'endtime',
                'repeat_group_path' => NULL,
                'path' => '/endtime',
                'type' => 'end',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "metadata_fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:47',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            43 =>
            array (
                'id' => 44,
                'xlsform_module_version_id' => 6,
                'row_number' => 4,
                'name' => 'todaydate',
                'repeat_group_path' => NULL,
                'path' => '/todaydate',
                'type' => 'today',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "metadata_fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:47',
                'updated_at' => '2025-03-24 10:46:48',
            ),
            44 =>
            array (
                'id' => 45,
                'xlsform_module_version_id' => 6,
                'row_number' => 5,
                'name' => 'deviceid',
                'repeat_group_path' => NULL,
                'path' => '/deviceid',
                'type' => 'deviceid',
                'choice_list_id' => NULL,
                'required' => 0,
                'relevant' => NULL,
                'appearance' => NULL,
                'calculation' => NULL,
                'constraint' => NULL,
                'choice_filter' => NULL,
                'repeat_count' => NULL,
                'default' => NULL,
                'note' => NULL,
                'trigger' => NULL,
                'properties' => '{"module": "metadata_fieldwork"}',
                'updated_during_import' => 0,
                'created_at' => '2025-01-07 17:00:47',
                'updated_at' => '2025-03-24 10:46:48',
            ),
        ));


    }
}
